package com.coffeeshop.repository;

import com.coffeeshop.dto.MenuCommands;
import com.coffeeshop.exception.DatabaseException;
import com.coffeeshop.model.MenuModels;
import javax.sql.DataSource;
import java.sql.*;
import java.util.*;

/** SQL Server persistence for menu administration with optimistic concurrency. */
public final class JdbcMenuManagementRepository implements MenuManagementRepository {
    private final DataSource dataSource;
    public JdbcMenuManagementRepository(DataSource dataSource){this.dataSource=Objects.requireNonNull(dataSource);}

    @Override public long saveCategory(MenuCommands.Category q){String insert="INSERT dbo.categories(category_name,description,display_order,is_active) VALUES(?,?,?,?)";String update="UPDATE dbo.categories SET category_name=?,description=?,display_order=?,is_active=?,updated_at=SYSUTCDATETIME() WHERE category_id=? AND row_version=?";try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(q.id()==null?insert:update,Statement.RETURN_GENERATED_KEYS)){s.setString(1,q.name());nullableString(s,2,q.description(),Types.NVARCHAR);s.setInt(3,q.displayOrder());s.setBoolean(4,q.active());if(q.id()!=null){s.setLong(5,q.id());s.setBytes(6,q.rowVersion());checkUpdated(s.executeUpdate());return q.id();}s.executeUpdate();return key(s);}catch(SQLException e){throw failure("Unable to save the category. Check that its name is unique.",e);}}
    @Override public void setCategoryActive(long id,boolean active,byte[] version){toggle("UPDATE dbo.categories SET is_active=?,updated_at=SYSUTCDATETIME() WHERE category_id=? AND row_version=?",id,active,version,"category");}

    @Override public MenuModels.Catalog loadCatalog(){
        try(Connection c=dataSource.getConnection()){
            List<MenuModels.Category> categories=categories(c);
            List<MenuModels.Lookup> categoryLookups=categories.stream().map(v->new MenuModels.Lookup(v.id(),"",v.name(),v.active())).toList();
            return new MenuModels.Catalog(categoryLookups,
                    lookups(c,"SELECT preparation_station_id,station_code,station_name,is_active FROM dbo.preparation_stations ORDER BY display_order,station_name"),
                    products(c),variants(c),groups(c),modifiers(c),assignments(c),categories);
        }catch(SQLException e){throw failure("Unable to load menu management data.",e);}
    }

    private List<MenuModels.Lookup>lookups(Connection c,String sql)throws SQLException{try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<MenuModels.Lookup>x=new ArrayList<>();while(r.next())x.add(new MenuModels.Lookup(r.getLong(1),r.getString(2),r.getString(3),r.getBoolean(4)));return List.copyOf(x);}}
    private List<MenuModels.Category>categories(Connection c)throws SQLException{String sql="SELECT category_id,category_name,description,display_order,is_active,row_version FROM dbo.categories ORDER BY display_order,category_name";try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<MenuModels.Category>x=new ArrayList<>();while(r.next())x.add(new MenuModels.Category(r.getLong(1),r.getString(2),r.getString(3),r.getInt(4),r.getBoolean(5),r.getBytes(6)));return List.copyOf(x);}}
    private List<MenuModels.Product>products(Connection c)throws SQLException{String sql="""
        SELECT p.product_id,p.category_id,p.preparation_station_id,p.product_code,p.product_name,p.description,p.image_path,
               p.display_order,p.is_active,c.category_name,s.station_name,p.row_version
        FROM dbo.products p JOIN dbo.categories c ON c.category_id=p.category_id
        LEFT JOIN dbo.preparation_stations s ON s.preparation_station_id=p.preparation_station_id
        ORDER BY p.display_order,p.product_name
        """;try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<MenuModels.Product>x=new ArrayList<>();while(r.next()){long station=r.getLong(3);x.add(new MenuModels.Product(r.getLong(1),r.getLong(2),r.wasNull()?null:station,r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getInt(8),r.getBoolean(9),r.getString(10),r.getString(11),r.getBytes(12)));}return List.copyOf(x);}}
    private List<MenuModels.Variant>variants(Connection c)throws SQLException{String sql="""
        SELECT v.product_variant_id,v.product_id,v.preparation_station_id,v.variant_code,v.variant_name,v.sku,v.selling_price,
               v.display_order,v.is_default,v.is_active,s.station_name,v.row_version
        FROM dbo.product_variants v LEFT JOIN dbo.preparation_stations s ON s.preparation_station_id=v.preparation_station_id
        ORDER BY v.product_id,v.display_order,v.variant_name
        """;try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<MenuModels.Variant>x=new ArrayList<>();while(r.next()){long station=r.getLong(3);x.add(new MenuModels.Variant(r.getLong(1),r.getLong(2),r.wasNull()?null:station,r.getString(4),r.getString(5),r.getString(6),r.getBigDecimal(7),r.getInt(8),r.getBoolean(9),r.getBoolean(10),r.getString(11),r.getBytes(12)));}return List.copyOf(x);}}
    private List<MenuModels.ModifierGroup>groups(Connection c)throws SQLException{String sql="SELECT modifier_group_id,group_code,group_name,description,minimum_selections,maximum_selections,display_order,is_active,row_version FROM dbo.modifier_groups ORDER BY display_order,group_name";try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<MenuModels.ModifierGroup>x=new ArrayList<>();while(r.next())x.add(new MenuModels.ModifierGroup(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getInt(5),r.getInt(6),r.getInt(7),r.getBoolean(8),r.getBytes(9)));return List.copyOf(x);}}
    private List<MenuModels.Modifier>modifiers(Connection c)throws SQLException{String sql="SELECT modifier_id,modifier_group_id,modifier_code,modifier_name,price_adjustment,display_order,is_active,row_version FROM dbo.modifiers ORDER BY modifier_group_id,display_order,modifier_name";try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<MenuModels.Modifier>x=new ArrayList<>();while(r.next())x.add(new MenuModels.Modifier(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getBigDecimal(5),r.getInt(6),r.getBoolean(7),r.getBytes(8)));return List.copyOf(x);}}
    private List<MenuModels.Assignment>assignments(Connection c)throws SQLException{String sql="""
        SELECT a.product_modifier_group_assignment_id,a.product_id,a.modifier_group_id,a.minimum_selections_override,
               a.maximum_selections_override,a.display_order,a.is_active,g.group_name,a.row_version
        FROM dbo.product_modifier_group_assignments a JOIN dbo.modifier_groups g ON g.modifier_group_id=a.modifier_group_id
        ORDER BY a.product_id,a.display_order,g.group_name
        """;try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<MenuModels.Assignment>x=new ArrayList<>();while(r.next()){int min=r.getInt(4);Integer minValue=r.wasNull()?null:min;int max=r.getInt(5);Integer maxValue=r.wasNull()?null:max;x.add(new MenuModels.Assignment(r.getLong(1),r.getLong(2),r.getLong(3),minValue,maxValue,r.getInt(6),r.getBoolean(7),r.getString(8),r.getBytes(9)));}return List.copyOf(x);}}

    @Override public long saveProduct(MenuCommands.Product q){String insert="INSERT dbo.products(category_id,preparation_station_id,product_code,product_name,description,image_path,display_order,is_active) VALUES(?,?,?,?,?,?,?,?)";String update="UPDATE dbo.products SET category_id=?,preparation_station_id=?,product_code=?,product_name=?,description=?,image_path=?,display_order=?,is_active=?,updated_at=SYSUTCDATETIME() WHERE product_id=? AND row_version=?";try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(q.id()==null?insert:update,Statement.RETURN_GENERATED_KEYS)){productParams(s,q);if(q.id()!=null){s.setLong(9,q.id());s.setBytes(10,q.rowVersion());checkUpdated(s.executeUpdate());return q.id();}s.executeUpdate();return key(s);}catch(SQLException e){throw failure("Unable to save the product. Check that its code is unique.",e);}}
    private void productParams(PreparedStatement s,MenuCommands.Product q)throws SQLException{s.setLong(1,q.categoryId());nullableLong(s,2,q.stationId());s.setString(3,q.code());s.setString(4,q.name());nullableString(s,5,q.description(),Types.NVARCHAR);nullableString(s,6,q.imagePath(),Types.NVARCHAR);s.setInt(7,q.displayOrder());s.setBoolean(8,q.active());}
    @Override public void setProductActive(long id,boolean active,byte[] version){toggle("UPDATE dbo.products SET is_active=?,updated_at=SYSUTCDATETIME() WHERE product_id=? AND row_version=?",id,active,version,"product");}

    @Override public long saveVariant(MenuCommands.Variant q){try(Connection c=dataSource.getConnection()){c.setAutoCommit(false);try{if(q.defaultVariant()&&q.active())try(PreparedStatement clear=c.prepareStatement("UPDATE dbo.product_variants SET is_default=0,updated_at=SYSUTCDATETIME() WHERE product_id=? AND is_default=1 AND product_variant_id<>?")){clear.setLong(1,q.productId());clear.setLong(2,q.id()==null?-1:q.id());clear.executeUpdate();}String insert="INSERT dbo.product_variants(product_id,preparation_station_id,variant_code,variant_name,sku,selling_price,display_order,is_default,is_active) VALUES(?,?,?,?,?,?,?,?,?)";String update="UPDATE dbo.product_variants SET product_id=?,preparation_station_id=?,variant_code=?,variant_name=?,sku=?,selling_price=?,display_order=?,is_default=?,is_active=?,updated_at=SYSUTCDATETIME() WHERE product_variant_id=? AND row_version=?";long id;try(PreparedStatement s=c.prepareStatement(q.id()==null?insert:update,Statement.RETURN_GENERATED_KEYS)){variantParams(s,q);if(q.id()!=null){s.setLong(10,q.id());s.setBytes(11,q.rowVersion());checkUpdated(s.executeUpdate());id=q.id();}else{s.executeUpdate();id=key(s);}}c.commit();return id;}catch(Exception e){c.rollback();throw e;}}catch(RuntimeException e){throw e;}catch(Exception e){throw failure("Unable to save the variant. Check its code, SKU, and default selection.",e);}}
    private void variantParams(PreparedStatement s,MenuCommands.Variant q)throws SQLException{s.setLong(1,q.productId());nullableLong(s,2,q.stationId());s.setString(3,q.code());s.setString(4,q.name());nullableString(s,5,q.sku(),Types.VARCHAR);s.setBigDecimal(6,q.price());s.setInt(7,q.displayOrder());s.setBoolean(8,q.defaultVariant());s.setBoolean(9,q.active());}
    @Override public void setVariantActive(long id,long productId,boolean defaultVariant,boolean active,byte[] version){try(Connection c=dataSource.getConnection()){c.setAutoCommit(false);try{if(active&&defaultVariant)try(PreparedStatement clear=c.prepareStatement("UPDATE dbo.product_variants SET is_default=0,updated_at=SYSUTCDATETIME() WHERE product_id=? AND is_default=1 AND is_active=1 AND product_variant_id<>?")){clear.setLong(1,productId);clear.setLong(2,id);clear.executeUpdate();}try(PreparedStatement update=c.prepareStatement("UPDATE dbo.product_variants SET is_active=?,updated_at=SYSUTCDATETIME() WHERE product_variant_id=? AND row_version=?")){update.setBoolean(1,active);update.setLong(2,id);update.setBytes(3,version);checkUpdated(update.executeUpdate());}c.commit();}catch(Exception e){c.rollback();throw e;}}catch(RuntimeException e){throw e;}catch(Exception e){throw failure("Unable to update the variant status.",e);}}

    @Override public long saveGroup(MenuCommands.Group q){String insert="INSERT dbo.modifier_groups(group_code,group_name,description,minimum_selections,maximum_selections,display_order,is_active) VALUES(?,?,?,?,?,?,?)";String update="UPDATE dbo.modifier_groups SET group_code=?,group_name=?,description=?,minimum_selections=?,maximum_selections=?,display_order=?,is_active=?,updated_at=SYSUTCDATETIME() WHERE modifier_group_id=? AND row_version=?";try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(q.id()==null?insert:update,Statement.RETURN_GENERATED_KEYS)){s.setString(1,q.code());s.setString(2,q.name());nullableString(s,3,q.description(),Types.NVARCHAR);s.setInt(4,q.minimumSelections());s.setInt(5,q.maximumSelections());s.setInt(6,q.displayOrder());s.setBoolean(7,q.active());if(q.id()!=null){s.setLong(8,q.id());s.setBytes(9,q.rowVersion());checkUpdated(s.executeUpdate());return q.id();}s.executeUpdate();return key(s);}catch(SQLException e){throw failure("Unable to save the modifier group. Check that its code and name are unique.",e);}}
    @Override public void setGroupActive(long id,boolean active,byte[] version){toggle("UPDATE dbo.modifier_groups SET is_active=?,updated_at=SYSUTCDATETIME() WHERE modifier_group_id=? AND row_version=?",id,active,version,"modifier group");}

    @Override public long saveModifier(MenuCommands.Modifier q){String insert="INSERT dbo.modifiers(modifier_group_id,modifier_code,modifier_name,price_adjustment,display_order,is_active) VALUES(?,?,?,?,?,?)";String update="UPDATE dbo.modifiers SET modifier_group_id=?,modifier_code=?,modifier_name=?,price_adjustment=?,display_order=?,is_active=?,updated_at=SYSUTCDATETIME() WHERE modifier_id=? AND row_version=?";try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(q.id()==null?insert:update,Statement.RETURN_GENERATED_KEYS)){s.setLong(1,q.groupId());s.setString(2,q.code());s.setString(3,q.name());s.setBigDecimal(4,q.priceAdjustment());s.setInt(5,q.displayOrder());s.setBoolean(6,q.active());if(q.id()!=null){s.setLong(7,q.id());s.setBytes(8,q.rowVersion());checkUpdated(s.executeUpdate());return q.id();}s.executeUpdate();return key(s);}catch(SQLException e){throw failure("Unable to save the modifier. Check that its code and name are unique within the group.",e);}}
    @Override public void setModifierActive(long id,boolean active,byte[] version){toggle("UPDATE dbo.modifiers SET is_active=?,updated_at=SYSUTCDATETIME() WHERE modifier_id=? AND row_version=?",id,active,version,"modifier");}

    @Override public long saveAssignment(MenuCommands.Assignment q){String insert="INSERT dbo.product_modifier_group_assignments(product_id,modifier_group_id,minimum_selections_override,maximum_selections_override,display_order,is_active) VALUES(?,?,?,?,?,?)";String update="UPDATE dbo.product_modifier_group_assignments SET product_id=?,modifier_group_id=?,minimum_selections_override=?,maximum_selections_override=?,display_order=?,is_active=?,updated_at=SYSUTCDATETIME() WHERE product_modifier_group_assignment_id=? AND row_version=?";try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(q.id()==null?insert:update,Statement.RETURN_GENERATED_KEYS)){s.setLong(1,q.productId());s.setLong(2,q.groupId());nullableInt(s,3,q.minimumOverride());nullableInt(s,4,q.maximumOverride());s.setInt(5,q.displayOrder());s.setBoolean(6,q.active());if(q.id()!=null){s.setLong(7,q.id());s.setBytes(8,q.rowVersion());checkUpdated(s.executeUpdate());return q.id();}s.executeUpdate();return key(s);}catch(SQLException e){throw failure("Unable to save the modifier assignment. The group may already be assigned.",e);}}
    @Override public void setAssignmentActive(long id,boolean active,byte[] version){toggle("UPDATE dbo.product_modifier_group_assignments SET is_active=?,updated_at=SYSUTCDATETIME() WHERE product_modifier_group_assignment_id=? AND row_version=?",id,active,version,"assignment");}

    private void toggle(String sql,long id,boolean active,byte[] version,String entity){try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setBoolean(1,active);s.setLong(2,id);s.setBytes(3,version);checkUpdated(s.executeUpdate());}catch(SQLException e){throw failure("Unable to update the "+entity+" status.",e);}}
    private static void checkUpdated(int count){if(count!=1)throw new IllegalStateException("This record changed. Refresh and try again.");}
    private static long key(PreparedStatement s)throws SQLException{try(ResultSet r=s.getGeneratedKeys()){if(!r.next())throw new SQLException("Generated identifier was unavailable");return r.getLong(1);}}
    private static void nullableLong(PreparedStatement s,int index,Long value)throws SQLException{if(value==null)s.setNull(index,Types.BIGINT);else s.setLong(index,value);}
    private static void nullableInt(PreparedStatement s,int index,Integer value)throws SQLException{if(value==null)s.setNull(index,Types.SMALLINT);else s.setInt(index,value);}
    private static void nullableString(PreparedStatement s,int index,String value,int type)throws SQLException{if(value==null)s.setNull(index,type);else s.setString(index,value);}
    private static DatabaseException failure(String message,Exception cause){return new DatabaseException(message,cause);}
}
