package com.coffeeshop.repository;

import com.coffeeshop.dto.RegisterCommands;
import com.coffeeshop.exception.DatabaseException;
import com.coffeeshop.model.RegisterModels;
import javax.sql.DataSource;
import java.math.BigDecimal;
import java.sql.*;
import java.util.*;

/** SQL Server register persistence with locked shift lifecycle and immutable cash history. */
public final class JdbcRegisterRepository implements RegisterRepository {
    private final DataSource dataSource;
    public JdbcRegisterRepository(DataSource dataSource){this.dataSource=Objects.requireNonNull(dataSource);}

    @Override public RegisterModels.Dashboard loadDashboard(long userId,boolean includeAllHistory){try(Connection c=dataSource.getConnection()){List<RegisterModels.Register> registers=registers(c);RegisterModels.Shift current=currentShift(c,userId);List<RegisterModels.Shift> history=shiftHistory(c,userId,includeAllHistory);List<RegisterModels.CashMovement> movements=current==null?List.of():movements(c,current.id());return new RegisterModels.Dashboard(registers,current,history,movements);}catch(SQLException e){throw failure("Unable to load register and shift data.",e);}}
    private List<RegisterModels.Register> registers(Connection c)throws SQLException{String sql="SELECT register_id,register_code,register_name,display_order,is_active,row_version FROM dbo.registers ORDER BY display_order,register_name";try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<RegisterModels.Register> out=new ArrayList<>();while(r.next())out.add(new RegisterModels.Register(r.getLong(1),r.getString(2),r.getString(3),r.getInt(4),r.getBoolean(5),r.getBytes(6)));return List.copyOf(out);}}
    private RegisterModels.Shift currentShift(Connection c,long userId)throws SQLException{String sql=shiftSelect()+" WHERE rs.opened_by_user_id=? AND rs.status='OPEN'";try(PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,userId);try(ResultSet r=s.executeQuery()){return r.next()?mapShift(r):null;}}}
    private List<RegisterModels.Shift> shiftHistory(Connection c,long userId,boolean all)throws SQLException{String sql=shiftSelect()+(all?"":" WHERE rs.opened_by_user_id=?")+" ORDER BY rs.opened_at DESC";try(PreparedStatement s=c.prepareStatement(sql)){if(!all)s.setLong(1,userId);try(ResultSet r=s.executeQuery()){List<RegisterModels.Shift> out=new ArrayList<>();while(r.next()&&out.size()<200)out.add(mapShift(r));return List.copyOf(out);}}}
    private static String shiftSelect(){return """
        SELECT rs.register_shift_id,rs.register_id,r.register_code,r.register_name,rs.opened_by_user_id,u.username,
               rs.opened_at,rs.closed_at,rs.opening_cash,
               COALESCE(rs.expected_closing_cash,rs.opening_cash
                 + COALESCE((SELECT SUM(p.amount) FROM dbo.payments p JOIN dbo.payment_methods pm ON pm.payment_method_id=p.payment_method_id WHERE p.register_shift_id=rs.register_shift_id AND pm.method_code='CASH' AND p.status<>'VOIDED'),0) - COALESCE((SELECT SUM(pr.amount) FROM dbo.payment_refunds pr JOIN dbo.payments rp ON rp.payment_id=pr.payment_id JOIN dbo.payment_methods rpm ON rpm.payment_method_id=rp.payment_method_id WHERE pr.register_shift_id=rs.register_shift_id AND rpm.method_code='CASH'),0)
                 + COALESCE((SELECT SUM(CASE cm.movement_type WHEN 'CASH_IN' THEN cm.amount ELSE -cm.amount END) FROM dbo.cash_movements cm WHERE cm.register_shift_id=rs.register_shift_id),0)),
               rs.actual_closing_cash,rs.cash_difference,rs.status,rs.row_version
        FROM dbo.register_shifts rs JOIN dbo.registers r ON r.register_id=rs.register_id JOIN dbo.users u ON u.user_id=rs.opened_by_user_id
        """;}
    private static RegisterModels.Shift mapShift(ResultSet r)throws SQLException{Timestamp closed=r.getTimestamp(8);return new RegisterModels.Shift(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getLong(5),r.getString(6),r.getTimestamp(7).toLocalDateTime(),closed==null?null:closed.toLocalDateTime(),r.getBigDecimal(9),r.getBigDecimal(10),r.getBigDecimal(11),r.getBigDecimal(12),r.getString(13),r.getBytes(14));}
    private List<RegisterModels.CashMovement> movements(Connection c,long shiftId)throws SQLException{String sql="SELECT cm.cash_movement_id,cm.register_shift_id,cm.movement_type,cm.amount,cm.reason,cm.reference_number,cm.notes,cm.moved_at,u.username FROM dbo.cash_movements cm JOIN dbo.users u ON u.user_id=cm.recorded_by_user_id WHERE cm.register_shift_id=? ORDER BY cm.moved_at DESC,cm.cash_movement_id DESC";try(PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,shiftId);try(ResultSet r=s.executeQuery()){List<RegisterModels.CashMovement> out=new ArrayList<>();while(r.next())out.add(new RegisterModels.CashMovement(r.getLong(1),r.getLong(2),RegisterModels.CashMovementType.valueOf(r.getString(3)),r.getBigDecimal(4),r.getString(5),r.getString(6),r.getString(7),r.getTimestamp(8).toLocalDateTime(),r.getString(9)));return List.copyOf(out);}}}

    @Override public long saveRegister(RegisterCommands.Register q){String insert="INSERT dbo.registers(register_code,register_name,display_order,is_active) VALUES(?,?,?,?)";String update="UPDATE dbo.registers SET register_code=?,register_name=?,display_order=?,is_active=?,updated_at=SYSUTCDATETIME() WHERE register_id=? AND row_version=?";try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(q.id()==null?insert:update,Statement.RETURN_GENERATED_KEYS)){s.setString(1,q.code());s.setString(2,q.name());s.setInt(3,q.displayOrder());s.setBoolean(4,q.active());if(q.id()!=null){s.setLong(5,q.id());s.setBytes(6,q.rowVersion());updated(s.executeUpdate());return q.id();}s.executeUpdate();return key(s);}catch(SQLException e){throw failure("Unable to save the register. Check that its code is unique.",e);}}
    @Override public void setRegisterActive(long id,boolean active,byte[] version){try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement("UPDATE dbo.registers SET is_active=?,updated_at=SYSUTCDATETIME() WHERE register_id=? AND row_version=?")){s.setBoolean(1,active);s.setLong(2,id);s.setBytes(3,version);updated(s.executeUpdate());}catch(SQLException e){throw failure("Unable to update the register status.",e);}}
    @Override public long openShift(RegisterCommands.OpenShift q){try(Connection c=dataSource.getConnection()){c.setAutoCommit(false);c.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);try{try(PreparedStatement s=c.prepareStatement("SELECT register_shift_id FROM dbo.register_shifts WITH(UPDLOCK,HOLDLOCK) WHERE opened_by_user_id=? AND status='OPEN'")){s.setLong(1,q.userId());try(ResultSet r=s.executeQuery()){if(r.next())throw new IllegalStateException("You already have an open register shift.");}}try(PreparedStatement s=c.prepareStatement("SELECT r.is_active,(SELECT COUNT(*) FROM dbo.register_shifts rs WITH(UPDLOCK,HOLDLOCK) WHERE rs.register_id=r.register_id AND rs.status='OPEN') FROM dbo.registers r WITH(UPDLOCK,HOLDLOCK) WHERE r.register_id=?")){s.setLong(1,q.registerId());try(ResultSet r=s.executeQuery()){if(!r.next()||!r.getBoolean(1))throw new IllegalStateException("The selected register is not active.");if(r.getInt(2)>0)throw new IllegalStateException("The selected register already has an open shift.");}}long id;try(PreparedStatement s=c.prepareStatement("INSERT dbo.register_shifts(register_id,opened_by_user_id,opening_cash) VALUES(?,?,?)",Statement.RETURN_GENERATED_KEYS)){s.setLong(1,q.registerId());s.setLong(2,q.userId());s.setBigDecimal(3,q.openingCash());s.executeUpdate();id=key(s);}c.commit();return id;}catch(Exception e){c.rollback();throw e;}}catch(RuntimeException e){throw e;}catch(Exception e){throw failure("Unable to open the register shift.",e);}}
    @Override public long recordCashMovement(RegisterCommands.CashMovement q){try(Connection c=dataSource.getConnection()){c.setAutoCommit(false);c.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);try{lockOwnedOpenShift(c,q.shiftId(),q.userId(),null);if(q.type()==RegisterModels.CashMovementType.CASH_OUT&&expectedCash(c,q.shiftId()).compareTo(q.amount())<0)throw new IllegalStateException("Cash out cannot exceed the shift's expected cash.");long id;try(PreparedStatement s=c.prepareStatement("INSERT dbo.cash_movements(register_shift_id,recorded_by_user_id,movement_type,amount,reason,reference_number,notes) VALUES(?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){s.setLong(1,q.shiftId());s.setLong(2,q.userId());s.setString(3,q.type().name());s.setBigDecimal(4,q.amount());s.setString(5,q.reason());nullable(s,6,q.reference(),Types.NVARCHAR);nullable(s,7,q.notes(),Types.NVARCHAR);s.executeUpdate();id=key(s);}c.commit();return id;}catch(Exception e){c.rollback();throw e;}}catch(RuntimeException e){throw e;}catch(Exception e){throw failure("Unable to record the cash movement.",e);}}
    @Override public void closeShift(RegisterCommands.CloseShift q){try(Connection c=dataSource.getConnection()){c.setAutoCommit(false);c.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);try{lockOwnedOpenShift(c,q.shiftId(),q.userId(),q.rowVersion());BigDecimal expected=expectedCash(c,q.shiftId());if(expected.signum()<0)throw new IllegalStateException("Expected cash cannot be negative. Review the shift movements.");BigDecimal difference=q.actualCash().subtract(expected).setScale(4);if(difference.signum()!=0){if(!q.varianceAuthorized())throw new SecurityException("A manager or administrator must close a shift with a cash variance.");if(q.varianceReason()==null)throw new IllegalArgumentException("A reason is required for a cash variance.");}try(PreparedStatement s=c.prepareStatement("UPDATE dbo.register_shifts SET closed_by_user_id=?,closed_at=SYSUTCDATETIME(),expected_closing_cash=?,actual_closing_cash=?,cash_difference=?,status='CLOSED',updated_at=SYSUTCDATETIME() WHERE register_shift_id=? AND status='OPEN' AND row_version=?")){s.setLong(1,q.userId());s.setBigDecimal(2,expected);s.setBigDecimal(3,q.actualCash());s.setBigDecimal(4,difference);s.setLong(5,q.shiftId());s.setBytes(6,q.rowVersion());updated(s.executeUpdate());}if(difference.signum()!=0)try(PreparedStatement s=c.prepareStatement("INSERT dbo.audit_logs(user_id,action_code,entity_type,entity_id,details,reason) VALUES(?,'REGISTER_SHIFT_VARIANCE','REGISTER_SHIFT',?,?,?)")){s.setLong(1,q.userId());s.setLong(2,q.shiftId());s.setString(3,"Expected "+expected.toPlainString()+", actual "+q.actualCash().toPlainString()+", difference "+difference.toPlainString());s.setString(4,q.varianceReason());s.executeUpdate();}c.commit();}catch(Exception e){c.rollback();throw e;}}catch(RuntimeException e){throw e;}catch(Exception e){throw failure("Unable to close the register shift.",e);}}
    private static void lockOwnedOpenShift(Connection c,long shiftId,long userId,byte[] version)throws SQLException{String sql="SELECT row_version FROM dbo.register_shifts WITH(UPDLOCK,HOLDLOCK) WHERE register_shift_id=? AND opened_by_user_id=? AND status='OPEN'";try(PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,shiftId);s.setLong(2,userId);try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalStateException("The register shift is no longer open.");if(version!=null&&!Arrays.equals(version,r.getBytes(1)))throw new IllegalStateException("The register shift changed. Refresh and try again.");}}}
    private static BigDecimal expectedCash(Connection c,long shiftId)throws SQLException{String sql="""
        SELECT rs.opening_cash
          + COALESCE((SELECT SUM(p.amount) FROM dbo.payments p JOIN dbo.payment_methods pm ON pm.payment_method_id=p.payment_method_id WHERE p.register_shift_id=rs.register_shift_id AND pm.method_code='CASH' AND p.status<>'VOIDED'),0) - COALESCE((SELECT SUM(pr.amount) FROM dbo.payment_refunds pr JOIN dbo.payments rp ON rp.payment_id=pr.payment_id JOIN dbo.payment_methods rpm ON rpm.payment_method_id=rp.payment_method_id WHERE pr.register_shift_id=rs.register_shift_id AND rpm.method_code='CASH'),0)
          + COALESCE((SELECT SUM(CASE cm.movement_type WHEN 'CASH_IN' THEN cm.amount ELSE -cm.amount END) FROM dbo.cash_movements cm WHERE cm.register_shift_id=rs.register_shift_id),0)
        FROM dbo.register_shifts rs WHERE rs.register_shift_id=?
        """;try(PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,shiftId);try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalStateException("Register shift was not found.");return r.getBigDecimal(1).setScale(4);}}}
    private static void nullable(PreparedStatement s,int index,String value,int type)throws SQLException{if(value==null)s.setNull(index,type);else s.setString(index,value);}
    private static void updated(int count){if(count!=1)throw new IllegalStateException("This record changed. Refresh and try again.");}
    private static long key(PreparedStatement s)throws SQLException{try(ResultSet r=s.getGeneratedKeys()){if(!r.next())throw new SQLException("Generated identifier was unavailable");return r.getLong(1);}}
    private static DatabaseException failure(String message,Exception cause){return new DatabaseException(message,cause);}
}
