package com.coffeeshop.repository;

import com.coffeeshop.dto.InventoryCommands;
import com.coffeeshop.exception.DatabaseException;
import com.coffeeshop.model.InventoryModels;
import com.coffeeshop.validation.InventoryValidator;
import javax.sql.DataSource;
import java.math.BigDecimal;
import java.sql.*;
import java.util.*;

/** SQL Server inventory persistence with immutable movements and optimistic recipe edits. */
public final class JdbcInventoryRepository implements InventoryRepository {
    private final DataSource dataSource;
    public JdbcInventoryRepository(DataSource dataSource){this.dataSource=Objects.requireNonNull(dataSource);}

    @Override public InventoryModels.Catalog loadCatalog(){try(Connection c=dataSource.getConnection()){return new InventoryModels.Catalog(units(c),items(c),movements(c),variants(c),modifiers(c),recipes(c),modifierRecipes(c));}catch(SQLException e){throw failure("Unable to load inventory data.",e);}}
    private List<InventoryModels.Lookup> units(Connection c)throws SQLException{return lookups(c,"SELECT unit_of_measure_id,unit_code,unit_name,is_active FROM dbo.units_of_measure ORDER BY unit_name");}
    private List<InventoryModels.Lookup> lookups(Connection c,String sql)throws SQLException{try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<InventoryModels.Lookup> out=new ArrayList<>();while(r.next())out.add(new InventoryModels.Lookup(r.getLong(1),r.getString(2),r.getString(3),r.getBoolean(4)));return List.copyOf(out);}}
    private List<InventoryModels.Item> items(Connection c)throws SQLException{String sql="SELECT i.inventory_item_id,i.unit_of_measure_id,i.item_code,i.item_name,i.current_stock_quantity,i.reorder_level,i.allow_negative_stock,i.is_active,u.unit_name,i.row_version FROM dbo.inventory_items i JOIN dbo.units_of_measure u ON u.unit_of_measure_id=i.unit_of_measure_id ORDER BY i.item_name";try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<InventoryModels.Item> out=new ArrayList<>();while(r.next())out.add(new InventoryModels.Item(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getBigDecimal(5),r.getBigDecimal(6),r.getBoolean(7),r.getBoolean(8),r.getString(9),r.getBytes(10)));return List.copyOf(out);}}
    private List<InventoryModels.Movement> movements(Connection c)throws SQLException{String sql="SELECT TOP (500) m.inventory_movement_id,m.inventory_item_id,m.movement_type,m.quantity_delta,m.reason,m.notes,m.occurred_at,u.username FROM dbo.inventory_movements m LEFT JOIN dbo.users u ON u.user_id=m.recorded_by_user_id ORDER BY m.occurred_at DESC,m.inventory_movement_id DESC";try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<InventoryModels.Movement> out=new ArrayList<>();while(r.next())out.add(new InventoryModels.Movement(r.getLong(1),r.getLong(2),r.getString(3),r.getBigDecimal(4),r.getString(5),r.getString(6),r.getTimestamp(7).toLocalDateTime(),r.getString(8)));return List.copyOf(out);}}
    private List<InventoryModels.Variant> variants(Connection c)throws SQLException{String sql="SELECT v.product_variant_id,p.product_id,p.product_name,v.variant_name,CASE WHEN p.is_active=1 AND v.is_active=1 THEN 1 ELSE 0 END FROM dbo.product_variants v JOIN dbo.products p ON p.product_id=v.product_id ORDER BY p.product_name,v.display_order,v.variant_name";try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<InventoryModels.Variant> out=new ArrayList<>();while(r.next())out.add(new InventoryModels.Variant(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4),r.getBoolean(5)));return List.copyOf(out);}}
    private List<InventoryModels.Modifier> modifiers(Connection c)throws SQLException{String sql="SELECT m.modifier_id,g.group_name,m.modifier_name,CASE WHEN g.is_active=1 AND m.is_active=1 THEN 1 ELSE 0 END FROM dbo.modifiers m JOIN dbo.modifier_groups g ON g.modifier_group_id=m.modifier_group_id ORDER BY g.display_order,g.group_name,m.display_order,m.modifier_name";try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<InventoryModels.Modifier> out=new ArrayList<>();while(r.next())out.add(new InventoryModels.Modifier(r.getLong(1),r.getString(2),r.getString(3),r.getBoolean(4)));return List.copyOf(out);}}
    private List<InventoryModels.RecipeItem> recipes(Connection c)throws SQLException{String sql="SELECT r.recipe_item_id,r.product_variant_id,r.inventory_item_id,i.item_name,u.unit_name,r.quantity_required,r.row_version FROM dbo.recipe_items r JOIN dbo.inventory_items i ON i.inventory_item_id=r.inventory_item_id JOIN dbo.units_of_measure u ON u.unit_of_measure_id=i.unit_of_measure_id ORDER BY r.product_variant_id,i.item_name";try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<InventoryModels.RecipeItem> out=new ArrayList<>();while(r.next())out.add(new InventoryModels.RecipeItem(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getString(5),r.getBigDecimal(6),r.getBytes(7)));return List.copyOf(out);}}
    private List<InventoryModels.ModifierRecipeItem> modifierRecipes(Connection c)throws SQLException{String sql="SELECT r.modifier_recipe_item_id,r.modifier_id,r.inventory_item_id,i.item_name,u.unit_name,r.quantity_required,r.row_version FROM dbo.modifier_recipe_items r JOIN dbo.inventory_items i ON i.inventory_item_id=r.inventory_item_id JOIN dbo.units_of_measure u ON u.unit_of_measure_id=i.unit_of_measure_id ORDER BY r.modifier_id,i.item_name";try(PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){List<InventoryModels.ModifierRecipeItem> out=new ArrayList<>();while(r.next())out.add(new InventoryModels.ModifierRecipeItem(r.getLong(1),r.getLong(2),r.getLong(3),r.getString(4),r.getString(5),r.getBigDecimal(6),r.getBytes(7)));return List.copyOf(out);}}

    @Override public long saveItem(InventoryCommands.Item q){String insert="INSERT dbo.inventory_items(unit_of_measure_id,item_code,item_name,reorder_level,allow_negative_stock,is_active) VALUES(?,?,?,?,?,?)";String update="UPDATE dbo.inventory_items SET unit_of_measure_id=?,item_code=?,item_name=?,reorder_level=?,allow_negative_stock=?,is_active=?,updated_at=SYSUTCDATETIME() WHERE inventory_item_id=? AND row_version=?";try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(q.id()==null?insert:update,Statement.RETURN_GENERATED_KEYS)){s.setLong(1,q.unitId());s.setString(2,q.code());s.setString(3,q.name());s.setBigDecimal(4,q.reorderLevel());s.setBoolean(5,q.allowNegative());s.setBoolean(6,q.active());if(q.id()!=null){s.setLong(7,q.id());s.setBytes(8,q.rowVersion());updated(s.executeUpdate());return q.id();}s.executeUpdate();return key(s);}catch(SQLException e){throw failure("Unable to save the inventory item. Check that its code and name are unique.",e);}}
    @Override public void setItemActive(long id,boolean active,byte[] version){try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement("UPDATE dbo.inventory_items SET is_active=?,updated_at=SYSUTCDATETIME() WHERE inventory_item_id=? AND row_version=?")){s.setBoolean(1,active);s.setLong(2,id);s.setBytes(3,version);updated(s.executeUpdate());}catch(SQLException e){throw failure("Unable to update the inventory item status.",e);}}
    @Override public void recordAdjustment(InventoryCommands.Adjustment q){try(Connection c=dataSource.getConnection()){c.setAutoCommit(false);c.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);try{BigDecimal stock;boolean allowNegative;try(PreparedStatement s=c.prepareStatement("SELECT current_stock_quantity,allow_negative_stock,is_active FROM dbo.inventory_items WITH(UPDLOCK,HOLDLOCK) WHERE inventory_item_id=?")){s.setLong(1,q.itemId());try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalArgumentException("Inventory item was not found.");if(!r.getBoolean(3))throw new IllegalStateException("Inactive inventory items cannot be adjusted.");stock=r.getBigDecimal(1);allowNegative=r.getBoolean(2);}}BigDecimal updatedStock=InventoryValidator.resultingStock(stock,q.quantityDelta(),allowNegative);try(PreparedStatement s=c.prepareStatement("INSERT dbo.inventory_movements(inventory_item_id,recorded_by_user_id,movement_type,quantity_delta,reason,notes) VALUES(?,?,'ADJUSTMENT',?,?,?)")){s.setLong(1,q.itemId());s.setLong(2,q.userId());s.setBigDecimal(3,q.quantityDelta());s.setString(4,q.reason());nullableString(s,5,q.notes());s.executeUpdate();}try(PreparedStatement s=c.prepareStatement("UPDATE dbo.inventory_items SET current_stock_quantity=?,updated_at=SYSUTCDATETIME() WHERE inventory_item_id=?")){s.setBigDecimal(1,updatedStock);s.setLong(2,q.itemId());updated(s.executeUpdate());}c.commit();}catch(Exception e){c.rollback();throw e;}}catch(RuntimeException e){throw e;}catch(Exception e){throw failure("Unable to record the stock adjustment.",e);}}
    @Override public long saveRecipe(InventoryCommands.Recipe q){String insert="INSERT dbo.recipe_items(product_variant_id,inventory_item_id,quantity_required) VALUES(?,?,?)";String update="UPDATE dbo.recipe_items SET product_variant_id=?,inventory_item_id=?,quantity_required=?,updated_at=SYSUTCDATETIME() WHERE recipe_item_id=? AND row_version=?";return saveRecipeRow(q.id(),q.variantId(),q.inventoryItemId(),q.quantityRequired(),q.rowVersion(),insert,update,"recipe ingredient");}
    @Override public long saveModifierRecipe(InventoryCommands.ModifierRecipe q){String insert="INSERT dbo.modifier_recipe_items(modifier_id,inventory_item_id,quantity_required) VALUES(?,?,?)";String update="UPDATE dbo.modifier_recipe_items SET modifier_id=?,inventory_item_id=?,quantity_required=?,updated_at=SYSUTCDATETIME() WHERE modifier_recipe_item_id=? AND row_version=?";return saveRecipeRow(q.id(),q.modifierId(),q.inventoryItemId(),q.quantityRequired(),q.rowVersion(),insert,update,"modifier ingredient");}
    private long saveRecipeRow(Long id,long ownerId,long itemId,BigDecimal quantity,byte[] version,String insert,String update,String label){try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(id==null?insert:update,Statement.RETURN_GENERATED_KEYS)){s.setLong(1,ownerId);s.setLong(2,itemId);s.setBigDecimal(3,quantity);if(id!=null){s.setLong(4,id);s.setBytes(5,version);updated(s.executeUpdate());return id;}s.executeUpdate();return key(s);}catch(SQLException e){throw failure("Unable to save the "+label+". The inventory item may already be linked.",e);}}
    @Override public void deleteRecipe(long id,byte[] version){deleteRecipeRow("DELETE FROM dbo.recipe_items WHERE recipe_item_id=? AND row_version=?",id,version,"recipe ingredient");}
    @Override public void deleteModifierRecipe(long id,byte[] version){deleteRecipeRow("DELETE FROM dbo.modifier_recipe_items WHERE modifier_recipe_item_id=? AND row_version=?",id,version,"modifier ingredient");}
    private void deleteRecipeRow(String sql,long id,byte[] version,String label){try(Connection c=dataSource.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,id);s.setBytes(2,version);updated(s.executeUpdate());}catch(SQLException e){throw failure("Unable to remove the "+label+".",e);}}
    private static void nullableString(PreparedStatement s,int index,String value)throws SQLException{if(value==null)s.setNull(index,Types.NVARCHAR);else s.setString(index,value);}
    private static void updated(int count){if(count!=1)throw new IllegalStateException("This record changed. Refresh and try again.");}
    private static long key(PreparedStatement s)throws SQLException{try(ResultSet r=s.getGeneratedKeys()){if(!r.next())throw new SQLException("Generated identifier was unavailable");return r.getLong(1);}}
    private static DatabaseException failure(String message,Exception cause){return new DatabaseException(message,cause);}
}
