package com.coffeeshop.service;
import com.coffeeshop.dto.*;import com.coffeeshop.model.*;import com.coffeeshop.repository.PosRepository;
import java.math.BigDecimal;import java.math.RoundingMode;import java.util.*;
/** Validates cashier order drafts before transactional persistence. */
public final class PosService {
 private final PosRepository repository; public PosService(PosRepository r){repository=Objects.requireNonNull(r);}
 public List<MenuCategory> categories(){return repository.findActiveCategories();} public List<MenuVariant> menu(){return repository.findActiveMenuVariants();} public List<CafeTableInfo> availableTables(){return repository.findAvailableTables();}
 public List<PosModifierGroup> modifierGroups(long productId){if(productId<=0)throw new IllegalArgumentException("Select a valid product.");return repository.findActiveModifierGroups(productId);}
 public List<SelectedModifier> validateModifierSelection(List<PosModifierGroup> groups,Collection<PosModifierOption> selected){Objects.requireNonNull(groups);Objects.requireNonNull(selected);Map<Long,PosModifierOption> selectedById=new LinkedHashMap<>();for(PosModifierOption option:selected){if(option==null||selectedById.putIfAbsent(option.modifierId(),option)!=null)throw new IllegalArgumentException("A modifier may only be selected once.");}Set<Long> allowed=new HashSet<>();for(PosModifierGroup group:groups){List<PosModifierOption> inGroup=group.options().stream().filter(o->selectedById.containsKey(o.modifierId())).toList();allowed.addAll(group.options().stream().map(PosModifierOption::modifierId).toList());if(inGroup.size()<group.minimumSelections())throw new IllegalArgumentException("Select at least "+group.minimumSelections()+" option(s) for "+group.name()+".");if(inGroup.size()>group.maximumSelections())throw new IllegalArgumentException("Select no more than "+group.maximumSelections()+" option(s) for "+group.name()+".");}if(!allowed.containsAll(selectedById.keySet()))throw new IllegalArgumentException("A selected modifier is not available for this product.");return selectedById.values().stream().map(o->new SelectedModifier(o.modifierId(),o.groupId(),o.name(),o.priceAdjustment())).toList();}
 public BigDecimal subtotal(Collection<CartLine> lines){return lines.stream().map(CartLine::subtotal).reduce(BigDecimal.ZERO,BigDecimal::add).setScale(4,RoundingMode.HALF_UP);}
 public String saveOpenOrder(CreateOrderRequest q){Objects.requireNonNull(q);if(q.userId()<=0)throw new IllegalArgumentException("An authenticated user is required.");if(q.lines().isEmpty())throw new IllegalArgumentException("Add at least one item.");if(q.orderType()==OrderType.DINE_IN&&q.cafeTableId()==null)throw new IllegalArgumentException("Select an available table.");if(q.orderType()==OrderType.DELIVERY)validateDelivery(q.deliveryInfo());return repository.createOpenOrder(q);}
 private static void validateDelivery(DeliveryInfo d){if(d==null||blank(d.recipientName())||blank(d.phone())||blank(d.addressLine1())||blank(d.city()))throw new IllegalArgumentException("Complete all required delivery details.");}
 private static boolean blank(String s){return s==null||s.isBlank();}
}
