package com.coffeeshop.controller;

import com.coffeeshop.dto.InventoryCommands;
import com.coffeeshop.exception.DatabaseException;
import com.coffeeshop.model.InventoryModels;
import com.coffeeshop.security.ApplicationSession;
import com.coffeeshop.service.InventoryService;
import javafx.application.Platform;
import javafx.beans.property.SimpleStringProperty;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.geometry.HPos;
import javafx.scene.Node;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.atomic.AtomicReference;

/** JavaFX coordination for inventory, immutable adjustments, and recipe configuration. */
public final class InventoryManagementController {
    private static final Logger LOGGER=LoggerFactory.getLogger(InventoryManagementController.class);
    private static final DateTimeFormatter DATE_TIME=DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
    private final InventoryService service;private final ApplicationSession session;private InventoryModels.Catalog catalog;
    @FXML private TextField itemSearch;@FXML private ChoiceBox<String> itemStatusFilter;
    @FXML private TableView<InventoryModels.Item> itemsTable;@FXML private TableView<InventoryModels.Movement> movementsTable;
    @FXML private TableView<InventoryModels.RecipeItem> recipesTable;@FXML private TableView<InventoryModels.ModifierRecipeItem> modifierRecipesTable;
    @FXML private ComboBox<InventoryModels.Variant> variantBox;@FXML private ComboBox<InventoryModels.Modifier> modifierBox;
    @FXML private TableColumn<InventoryModels.Item,String> itemCodeColumn,itemNameColumn,itemStockColumn,itemReorderColumn,itemStatusColumn;
    @FXML private TableColumn<InventoryModels.Movement,String> movementTimeColumn,movementTypeColumn,movementQuantityColumn,movementReasonColumn;
    @FXML private TableColumn<InventoryModels.RecipeItem,String> recipeItemColumn,recipeQuantityColumn,recipeUnitColumn;
    @FXML private TableColumn<InventoryModels.ModifierRecipeItem,String> modifierRecipeItemColumn,modifierRecipeQuantityColumn,modifierRecipeUnitColumn;
    @FXML private Button editItemButton,toggleItemButton,stockInButton,stockOutButton,addRecipeButton,editRecipeButton,removeRecipeButton,addModifierRecipeButton,editModifierRecipeButton,removeModifierRecipeButton;
    @FXML private Label selectedItemLabel,messageLabel;

    public InventoryManagementController(InventoryService service,ApplicationSession session){this.service=Objects.requireNonNull(service);this.session=Objects.requireNonNull(session);}
    @FXML private void initialize(){
        itemCodeColumn.setCellValueFactory(v->text(v.getValue().code()));itemNameColumn.setCellValueFactory(v->text(v.getValue().name()+" · "+v.getValue().unitName()));itemStockColumn.setCellValueFactory(v->text(number(v.getValue().stock())));itemReorderColumn.setCellValueFactory(v->text(number(v.getValue().reorderLevel())));itemStatusColumn.setCellValueFactory(v->text(v.getValue().active()?"Active":"Inactive"));
        movementTimeColumn.setCellValueFactory(v->text(v.getValue().occurredAt().format(DATE_TIME)));movementTypeColumn.setCellValueFactory(v->text(v.getValue().type()));movementQuantityColumn.setCellValueFactory(v->text(signed(v.getValue().quantityDelta())));movementReasonColumn.setCellValueFactory(v->text(orDash(v.getValue().reason())));
        recipeItemColumn.setCellValueFactory(v->text(v.getValue().inventoryItemName()));recipeQuantityColumn.setCellValueFactory(v->text(number(v.getValue().quantityRequired())));recipeUnitColumn.setCellValueFactory(v->text(v.getValue().unitName()));
        modifierRecipeItemColumn.setCellValueFactory(v->text(v.getValue().inventoryItemName()));modifierRecipeQuantityColumn.setCellValueFactory(v->text(number(v.getValue().quantityRequired())));modifierRecipeUnitColumn.setCellValueFactory(v->text(v.getValue().unitName()));
        itemStatusFilter.getItems().setAll("ALL","ACTIVE","INACTIVE","LOW STOCK");itemStatusFilter.setValue("ALL");itemSearch.textProperty().addListener((o,a,b)->filterItems());itemStatusFilter.valueProperty().addListener((o,a,b)->filterItems());itemsTable.getSelectionModel().selectedItemProperty().addListener((o,a,b)->selectItem(b));variantBox.valueProperty().addListener((o,a,b)->selectVariant(b));modifierBox.valueProperty().addListener((o,a,b)->selectModifier(b));recipesTable.getSelectionModel().selectedItemProperty().addListener((o,a,b)->updateButtons());modifierRecipesTable.getSelectionModel().selectedItemProperty().addListener((o,a,b)->updateButtons());
        itemsTable.setPlaceholder(new Label("No inventory items match this view."));movementsTable.setPlaceholder(new Label("No movements recorded for this item."));recipesTable.setPlaceholder(new Label("No ingredients configured for this variant."));modifierRecipesTable.setPlaceholder(new Label("No ingredients configured for this modifier."));updateButtons();refresh();
    }
    @FXML private void refresh(){message("Loading inventory data...",false);CompletableFuture.supplyAsync(service::catalog).whenComplete((value,error)->Platform.runLater(()->{if(error!=null){fail("Unable to load inventory data.",error);return;}catalog=value;variantBox.getItems().setAll(value.variants());modifierBox.getItems().setAll(value.modifiers());filterItems();if(!variantBox.getItems().isEmpty())variantBox.getSelectionModel().selectFirst();if(!modifierBox.getItems().isEmpty())modifierBox.getSelectionModel().selectFirst();message("Inventory data refreshed.",false);}));}
    private void filterItems(){if(catalog==null)return;String q=itemSearch.getText()==null?"":itemSearch.getText().trim().toLowerCase(Locale.ROOT);String status=itemStatusFilter.getValue();List<InventoryModels.Item> values=catalog.items().stream().filter(i->q.isEmpty()||(i.code()+" "+i.name()+" "+i.unitName()).toLowerCase(Locale.ROOT).contains(q)).filter(i->"ALL".equals(status)||"ACTIVE".equals(status)&&i.active()||"INACTIVE".equals(status)&&!i.active()||"LOW STOCK".equals(status)&&i.stock().compareTo(i.reorderLevel())<=0).toList();itemsTable.getItems().setAll(values);if(values.isEmpty())selectItem(null);else itemsTable.getSelectionModel().selectFirst();}
    private void selectItem(InventoryModels.Item item){selectedItemLabel.setText(item==null?"Select an inventory item":item.name()+" · "+number(item.stock())+" "+item.unitName());movementsTable.getItems().setAll(item==null||catalog==null?List.of():catalog.movements().stream().filter(m->m.itemId()==item.id()).toList());updateButtons();}
    private void selectVariant(InventoryModels.Variant variant){recipesTable.getItems().setAll(variant==null||catalog==null?List.of():catalog.recipes().stream().filter(r->r.variantId()==variant.id()).toList());updateButtons();}
    private void selectModifier(InventoryModels.Modifier modifier){modifierRecipesTable.getItems().setAll(modifier==null||catalog==null?List.of():catalog.modifierRecipes().stream().filter(r->r.modifierId()==modifier.id()).toList());updateButtons();}
    private void updateButtons(){InventoryModels.Item item=selected(itemsTable);set(editItemButton,item!=null);set(toggleItemButton,item!=null);set(stockInButton,item!=null&&item.active());set(stockOutButton,item!=null&&item.active());if(item!=null)toggleItemButton.setText(item.active()?"Deactivate":"Activate");InventoryModels.Variant variant=variantBox.getValue();set(addRecipeButton,variant!=null&&variant.active());set(editRecipeButton,selected(recipesTable)!=null);set(removeRecipeButton,selected(recipesTable)!=null);InventoryModels.Modifier modifier=modifierBox.getValue();set(addModifierRecipeButton,modifier!=null&&modifier.active());set(editModifierRecipeButton,selected(modifierRecipesTable)!=null);set(removeModifierRecipeButton,selected(modifierRecipesTable)!=null);}

    @FXML private void addItem(){itemDialog(null).ifPresent(q->write(()->service.saveItem(q),"Inventory item saved."));}@FXML private void editItem(){InventoryModels.Item item=selected(itemsTable);if(item!=null)itemDialog(item).ifPresent(q->write(()->service.saveItem(q),"Inventory item saved."));}@FXML private void toggleItem(){InventoryModels.Item item=selected(itemsTable);if(item!=null&&confirm((item.active()?"Deactivate ":"Activate ")+item.name()+"?","Update inventory item"))write(()->{service.setItemActive(item,!item.active());return 0L;},"Inventory item status updated.");}
    @FXML private void stockIn(){adjustmentDialog(true);}@FXML private void stockOut(){adjustmentDialog(false);}private void adjustmentDialog(boolean addition){InventoryModels.Item item=selected(itemsTable);if(item==null)return;TextField quantity=field("");TextField reason=field("");TextArea notes=area("");formDialog((addition?"Add":"Remove")+" stock",List.of(row("Inventory item",new Label(item.name())),row("Quantity",quantity),row("Reason",reason),row("Notes",notes)),()->new AdjustmentInput(decimal(quantity,"Quantity"),reason.getText(),notes.getText())).ifPresent(input->write(()->{long user=session.currentUser().orElseThrow().userId();if(addition)service.addStock(item.id(),user,input.quantity(),input.reason(),input.notes());else service.removeStock(item.id(),user,input.quantity(),input.reason(),input.notes());return 0L;},"Stock adjustment recorded."));}
    private record AdjustmentInput(BigDecimal quantity,String reason,String notes) { }
    @FXML private void addRecipe(){InventoryModels.Variant owner=variantBox.getValue();if(owner!=null)recipeDialog(owner,null).ifPresent(q->write(()->service.saveRecipe(q),"Recipe ingredient saved."));}@FXML private void editRecipe(){InventoryModels.Variant owner=variantBox.getValue();InventoryModels.RecipeItem row=selected(recipesTable);if(owner!=null&&row!=null)recipeDialog(owner,row).ifPresent(q->write(()->service.saveRecipe(q),"Recipe ingredient saved."));}@FXML private void removeRecipe(){InventoryModels.RecipeItem row=selected(recipesTable);if(row!=null&&confirm("Remove "+row.inventoryItemName()+" from this recipe?","Remove recipe ingredient"))write(()->{service.deleteRecipe(row);return 0L;},"Recipe ingredient removed.");}
    @FXML private void addModifierRecipe(){InventoryModels.Modifier owner=modifierBox.getValue();if(owner!=null)modifierRecipeDialog(owner,null).ifPresent(q->write(()->service.saveModifierRecipe(q),"Modifier ingredient saved."));}@FXML private void editModifierRecipe(){InventoryModels.Modifier owner=modifierBox.getValue();InventoryModels.ModifierRecipeItem row=selected(modifierRecipesTable);if(owner!=null&&row!=null)modifierRecipeDialog(owner,row).ifPresent(q->write(()->service.saveModifierRecipe(q),"Modifier ingredient saved."));}@FXML private void removeModifierRecipe(){InventoryModels.ModifierRecipeItem row=selected(modifierRecipesTable);if(row!=null&&confirm("Remove "+row.inventoryItemName()+" from this modifier recipe?","Remove modifier ingredient"))write(()->{service.deleteModifierRecipe(row);return 0L;},"Modifier ingredient removed.");}

    private Optional<InventoryCommands.Item> itemDialog(InventoryModels.Item item){List<InventoryModels.Lookup> units=catalog.units().stream().filter(u->u.active()||item!=null&&u.id()==item.unitId()).toList();ComboBox<InventoryModels.Lookup> unit=combo(units,lookup(units,item==null?null:item.unitId()));TextField code=field(item==null?null:item.code()),name=field(item==null?null:item.name()),reorder=field(item==null?"0.0000":item.reorderLevel().toPlainString());CheckBox active=check(item==null||item.active());return formDialog(item==null?"Add inventory item":"Edit inventory item",List.of(row("Unit of measure",unit),row("Item code",code),row("Item name",name),row("Reorder level",reorder),row("Active",active)),()->new InventoryCommands.Item(item==null?null:item.id(),unit.getValue()==null?0:unit.getValue().id(),code.getText(),name.getText(),decimal(reorder,"Reorder level"),item!=null&&item.allowNegative(),active.isSelected(),item==null?null:item.rowVersion()));}
    private Optional<InventoryCommands.Recipe> recipeDialog(InventoryModels.Variant owner,InventoryModels.RecipeItem row){ComboBox<InventoryModels.Item> item=combo(availableItems(row==null?null:row.inventoryItemId()),inventoryItem(row==null?null:row.inventoryItemId()));TextField quantity=field(row==null?"":row.quantityRequired().toPlainString());return formDialog(row==null?"Add recipe ingredient":"Edit recipe ingredient",List.of(row("Variant",new Label(owner.toString())),row("Inventory item",item),row("Quantity required",quantity)),()->new InventoryCommands.Recipe(row==null?null:row.id(),owner.id(),item.getValue()==null?0:item.getValue().id(),decimal(quantity,"Quantity required"),row==null?null:row.rowVersion()));}
    private Optional<InventoryCommands.ModifierRecipe> modifierRecipeDialog(InventoryModels.Modifier owner,InventoryModels.ModifierRecipeItem row){ComboBox<InventoryModels.Item> item=combo(availableItems(row==null?null:row.inventoryItemId()),inventoryItem(row==null?null:row.inventoryItemId()));TextField quantity=field(row==null?"":row.quantityRequired().toPlainString());return formDialog(row==null?"Add modifier ingredient":"Edit modifier ingredient",List.of(row("Modifier",new Label(owner.toString())),row("Inventory item",item),row("Quantity required",quantity)),()->new InventoryCommands.ModifierRecipe(row==null?null:row.id(),owner.id(),item.getValue()==null?0:item.getValue().id(),decimal(quantity,"Quantity required"),row==null?null:row.rowVersion()));}
    private List<InventoryModels.Item> availableItems(Long current){return catalog.items().stream().filter(i->i.active()||current!=null&&i.id()==current).toList();}private InventoryModels.Item inventoryItem(Long id){return id==null?null:catalog.items().stream().filter(i->i.id()==id).findFirst().orElse(null);}
    private <T>Optional<T> formDialog(String title,List<Node[]> rows,java.util.function.Supplier<T> result){Dialog<T> dialog=new Dialog<>();dialog.setTitle(title);dialog.getDialogPane().getButtonTypes().addAll(ButtonType.CANCEL,ButtonType.OK);GridPane grid=new GridPane();grid.setHgap(12);grid.setVgap(9);ColumnConstraints labels=new ColumnConstraints(150,150,150);labels.setHalignment(HPos.RIGHT);ColumnConstraints controls=new ColumnConstraints(245,330,Double.MAX_VALUE);controls.setHgrow(Priority.ALWAYS);grid.getColumnConstraints().addAll(labels,controls);for(int i=0;i<rows.size();i++){grid.add(rows.get(i)[0],0,i);grid.add(rows.get(i)[1],1,i);GridPane.setHgrow(rows.get(i)[1],Priority.ALWAYS);}Label error=new Label();error.setWrapText(true);error.getStyleClass().add("status-error");dialog.getDialogPane().setContent(new VBox(8,grid,error));dialog.getDialogPane().setPrefWidth(555);AtomicReference<T> validated=new AtomicReference<>();Node ok=dialog.getDialogPane().lookupButton(ButtonType.OK);ok.addEventFilter(ActionEvent.ACTION,event->{try{validated.set(result.get());error.setText("");}catch(RuntimeException e){error.setText(e.getMessage());event.consume();}});dialog.setResultConverter(button->button==ButtonType.OK?validated.get():null);return dialog.showAndWait();}
    private void write(java.util.concurrent.Callable<Long> action,String success){message("Saving...",false);CompletableFuture.supplyAsync(()->{try{return action.call();}catch(Exception e){throw new java.util.concurrent.CompletionException(e);}}).whenComplete((value,error)->Platform.runLater(()->{if(error!=null){fail("Unable to save this inventory change.",error);return;}message(success,false);refresh();}));}
    private void fail(String fallback,Throwable error){Throwable cause=error;while(cause.getCause()!=null&&(cause instanceof java.util.concurrent.CompletionException||cause instanceof java.util.concurrent.ExecutionException))cause=cause.getCause();LOGGER.error("Inventory operation failed ({}).",cause.getClass().getSimpleName());message(cause instanceof IllegalArgumentException||cause instanceof IllegalStateException||cause instanceof DatabaseException?cause.getMessage():fallback,true);}
    private boolean confirm(String content,String header){Alert alert=new Alert(Alert.AlertType.CONFIRMATION,content,ButtonType.CANCEL,ButtonType.OK);alert.setHeaderText(header);return alert.showAndWait().orElse(ButtonType.CANCEL)==ButtonType.OK;}
    private void message(String value,boolean error){messageLabel.setText(value);messageLabel.getStyleClass().setAll(error?"status-error":"status-message");}
    private static String number(BigDecimal value){return value.stripTrailingZeros().toPlainString();}private static String signed(BigDecimal value){return (value.signum()>0?"+":"")+number(value);}private static String orDash(String value){return value==null?"-":value;}private static SimpleStringProperty text(String value){return new SimpleStringProperty(value);}private static <T>T selected(TableView<T> table){return table.getSelectionModel().getSelectedItem();}private static void set(Button button,boolean enabled){button.setDisable(!enabled);}
    private static TextField field(String value){TextField field=new TextField(value==null?"":value);field.setMaxWidth(Double.MAX_VALUE);return field;}private static TextArea area(String value){TextArea area=new TextArea(value==null?"":value);area.setPrefRowCount(2);area.setWrapText(true);return area;}private static CheckBox check(boolean selected){CheckBox box=new CheckBox();box.setSelected(selected);return box;}private static Node[] row(String label,Node control){Label fieldLabel=new Label(label);fieldLabel.setMinWidth(Label.USE_PREF_SIZE);return new Node[]{fieldLabel,control};}private static <T>ComboBox<T> combo(Collection<T> values,T selected){ComboBox<T> box=new ComboBox<>();box.getItems().setAll(values);box.setValue(selected);box.setMaxWidth(Double.MAX_VALUE);return box;}private static InventoryModels.Lookup lookup(List<InventoryModels.Lookup> values,Long id){return id==null?null:values.stream().filter(v->v.id()==id).findFirst().orElse(null);}private static BigDecimal decimal(TextField field,String label){try{return new BigDecimal(field.getText().trim());}catch(Exception e){throw new IllegalArgumentException(label+" must be a valid number.");}}
}
