package com.coffeeshop.controller;

import com.coffeeshop.dto.MenuCommands;
import com.coffeeshop.model.MenuModels;
import com.coffeeshop.service.MenuManagementService;
import javafx.application.Platform;
import javafx.beans.property.SimpleStringProperty;
import javafx.fxml.FXML;
import javafx.scene.Node;
import javafx.scene.control.*;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.ColumnConstraints;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import javafx.geometry.HPos;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.atomic.AtomicReference;
import javafx.event.ActionEvent;

/** Coordinates menu administration views; validation and persistence remain below the UI layer. */
public final class MenuManagementController {
    private static final Logger LOGGER=LoggerFactory.getLogger(MenuManagementController.class);
    private static final MenuModels.Lookup NO_STATION=new MenuModels.Lookup(0,"","Use product/default routing",true);
    private final MenuManagementService service;
    private MenuModels.Catalog catalog;

    @FXML private TextField productSearch;
    @FXML private ComboBox<MenuModels.Lookup> categoryFilter;
    @FXML private ChoiceBox<String> productStatusFilter;
    @FXML private TableView<MenuModels.Product> productsTable;
    @FXML private TableView<MenuModels.Variant> variantsTable;
    @FXML private TableView<MenuModels.Assignment> assignmentsTable;
    @FXML private TableView<MenuModels.ModifierGroup> groupsTable;
    @FXML private TableView<MenuModels.Modifier> modifiersTable;
    @FXML private TableView<MenuModels.Category> categoriesTable;
    @FXML private TableColumn<MenuModels.Product,String> productCodeColumn,productNameColumn,productCategoryColumn,productStationColumn,productStatusColumn;
    @FXML private TableColumn<MenuModels.Variant,String> variantCodeColumn,variantNameColumn,variantPriceColumn,variantDefaultColumn,variantStatusColumn;
    @FXML private TableColumn<MenuModels.Assignment,String> assignmentGroupColumn,assignmentRangeColumn,assignmentStatusColumn;
    @FXML private TableColumn<MenuModels.ModifierGroup,String> groupCodeColumn,groupNameColumn,groupRangeColumn,groupStatusColumn;
    @FXML private TableColumn<MenuModels.Modifier,String> modifierCodeColumn,modifierNameColumn,modifierPriceColumn,modifierStatusColumn;
    @FXML private TableColumn<MenuModels.Category,String> categoryNameColumn,categoryDescriptionColumn,categoryOrderColumn,categoryStatusColumn;
    @FXML private Button editProductButton,toggleProductButton,editVariantButton,toggleVariantButton,editAssignmentButton,toggleAssignmentButton,editGroupButton,toggleGroupButton,editModifierButton,toggleModifierButton;
    @FXML private Button editCategoryButton,toggleCategoryButton;
    @FXML private Label messageLabel;

    public MenuManagementController(MenuManagementService service){this.service=Objects.requireNonNull(service);}

    @FXML private void initialize(){
        productCodeColumn.setCellValueFactory(v->text(v.getValue().code()));productNameColumn.setCellValueFactory(v->text(v.getValue().name()));productCategoryColumn.setCellValueFactory(v->text(v.getValue().categoryName()));productStationColumn.setCellValueFactory(v->text(orDash(v.getValue().stationName())));productStatusColumn.setCellValueFactory(v->text(status(v.getValue().active())));
        variantCodeColumn.setCellValueFactory(v->text(v.getValue().code()));variantNameColumn.setCellValueFactory(v->text(v.getValue().name()));variantPriceColumn.setCellValueFactory(v->text(money(v.getValue().price())));variantDefaultColumn.setCellValueFactory(v->text(v.getValue().defaultVariant()?"Yes":"No"));variantStatusColumn.setCellValueFactory(v->text(status(v.getValue().active())));
        assignmentGroupColumn.setCellValueFactory(v->text(v.getValue().groupName()));assignmentRangeColumn.setCellValueFactory(v->text(range(v.getValue().minimumOverride(),v.getValue().maximumOverride())));assignmentStatusColumn.setCellValueFactory(v->text(status(v.getValue().active())));
        groupCodeColumn.setCellValueFactory(v->text(v.getValue().code()));groupNameColumn.setCellValueFactory(v->text(v.getValue().name()));groupRangeColumn.setCellValueFactory(v->text(range(v.getValue().minimumSelections(),v.getValue().maximumSelections())));groupStatusColumn.setCellValueFactory(v->text(status(v.getValue().active())));
        modifierCodeColumn.setCellValueFactory(v->text(v.getValue().code()));modifierNameColumn.setCellValueFactory(v->text(v.getValue().name()));modifierPriceColumn.setCellValueFactory(v->text(money(v.getValue().priceAdjustment())));modifierStatusColumn.setCellValueFactory(v->text(status(v.getValue().active())));
        categoryNameColumn.setCellValueFactory(v->text(v.getValue().name()));categoryDescriptionColumn.setCellValueFactory(v->text(orDash(v.getValue().description())));categoryOrderColumn.setCellValueFactory(v->text(Integer.toString(v.getValue().displayOrder())));categoryStatusColumn.setCellValueFactory(v->text(status(v.getValue().active())));
        categoryFilter.setCellFactory(v->lookupCell("All categories"));categoryFilter.setButtonCell(lookupCell("All categories"));
        productStatusFilter.getItems().setAll("ALL","ACTIVE","INACTIVE");productStatusFilter.setValue("ALL");
        productSearch.textProperty().addListener((o,a,b)->filterProducts());categoryFilter.valueProperty().addListener((o,a,b)->filterProducts());productStatusFilter.valueProperty().addListener((o,a,b)->filterProducts());
        productsTable.getSelectionModel().selectedItemProperty().addListener((o,a,b)->selectProduct(b));groupsTable.getSelectionModel().selectedItemProperty().addListener((o,a,b)->selectGroup(b));
        variantsTable.getSelectionModel().selectedItemProperty().addListener((o,a,b)->updateButtons());assignmentsTable.getSelectionModel().selectedItemProperty().addListener((o,a,b)->updateButtons());modifiersTable.getSelectionModel().selectedItemProperty().addListener((o,a,b)->updateButtons());
        categoriesTable.getSelectionModel().selectedItemProperty().addListener((o,a,b)->updateCategoryButtons(b));
        updateButtons();refresh();
    }

    @FXML private void refresh(){message("Loading menu data...",false);CompletableFuture.supplyAsync(service::catalog).whenComplete((value,error)->Platform.runLater(()->{if(error!=null){fail("Unable to load menu management data.",error);return;}catalog=value;categoryFilter.getItems().setAll(value.categories());categoriesTable.getItems().setAll(value.categoryRecords());filterProducts();groupsTable.getItems().setAll(value.groups());restoreSelections();if(!categoriesTable.getItems().isEmpty())categoriesTable.getSelectionModel().selectFirst();message("Menu data refreshed.",false);}));}
    private void restoreSelections(){if(!productsTable.getItems().isEmpty())productsTable.getSelectionModel().selectFirst();if(!groupsTable.getItems().isEmpty())groupsTable.getSelectionModel().selectFirst();updateButtons();}
    private void filterProducts(){if(catalog==null)return;String query=productSearch.getText()==null?"":productSearch.getText().trim().toLowerCase(Locale.ROOT);MenuModels.Lookup category=categoryFilter.getValue();String active=productStatusFilter.getValue();List<MenuModels.Product> values=catalog.products().stream().filter(p->query.isEmpty()||(p.code()+" "+p.name()).toLowerCase(Locale.ROOT).contains(query)).filter(p->category==null||p.categoryId()==category.id()).filter(p->"ALL".equals(active)||p.active()=="ACTIVE".equals(active)).toList();productsTable.getItems().setAll(values);if(values.isEmpty()){variantsTable.getItems().clear();assignmentsTable.getItems().clear();}else productsTable.getSelectionModel().selectFirst();updateButtons();}
    private void selectProduct(MenuModels.Product product){if(catalog==null||product==null){variantsTable.getItems().clear();assignmentsTable.getItems().clear();}else{variantsTable.getItems().setAll(catalog.variants().stream().filter(v->v.productId()==product.id()).toList());assignmentsTable.getItems().setAll(catalog.assignments().stream().filter(a->a.productId()==product.id()).toList());}updateButtons();}
    private void selectGroup(MenuModels.ModifierGroup group){if(catalog==null||group==null)modifiersTable.getItems().clear();else modifiersTable.getItems().setAll(catalog.modifiers().stream().filter(m->m.groupId()==group.id()).toList());updateButtons();}
    private void updateButtons(){MenuModels.Product p=productsTable.getSelectionModel().getSelectedItem();set(editProductButton,p!=null);set(toggleProductButton,p!=null);if(p!=null)toggleProductButton.setText(p.active()?"Deactivate":"Activate");MenuModels.Variant v=variantsTable.getSelectionModel().getSelectedItem();set(editVariantButton,v!=null);set(toggleVariantButton,v!=null);if(v!=null)toggleVariantButton.setText(v.active()?"Deactivate":"Activate");MenuModels.Assignment a=assignmentsTable.getSelectionModel().getSelectedItem();set(editAssignmentButton,a!=null);set(toggleAssignmentButton,a!=null);if(a!=null)toggleAssignmentButton.setText(a.active()?"Deactivate":"Activate");MenuModels.ModifierGroup g=groupsTable.getSelectionModel().getSelectedItem();set(editGroupButton,g!=null);set(toggleGroupButton,g!=null);if(g!=null)toggleGroupButton.setText(g.active()?"Deactivate":"Activate");MenuModels.Modifier m=modifiersTable.getSelectionModel().getSelectedItem();set(editModifierButton,m!=null);set(toggleModifierButton,m!=null);if(m!=null)toggleModifierButton.setText(m.active()?"Deactivate":"Activate");}
    private void updateCategoryButtons(MenuModels.Category category){set(editCategoryButton,category!=null);set(toggleCategoryButton,category!=null);if(category!=null)toggleCategoryButton.setText(category.active()?"Deactivate":"Activate");}

    @FXML private void addCategory(){categoryDialog(null).ifPresent(q->write(()->service.saveCategory(q),"Category saved."));}@FXML private void editCategory(){MenuModels.Category c=selected(categoriesTable);if(c!=null)categoryDialog(c).ifPresent(q->write(()->service.saveCategory(q),"Category saved."));}@FXML private void toggleCategory(){MenuModels.Category c=selected(categoriesTable);if(c!=null&&confirmStatus(c.name(),c.active()))write(()->{service.setCategoryActive(c,!c.active());return 0L;},"Category status updated.");}
    @FXML private void addProduct(){productDialog(null).ifPresent(q->write(()->service.saveProduct(q),"Product saved."));}@FXML private void editProduct(){MenuModels.Product p=selected(productsTable);if(p!=null)productDialog(p).ifPresent(q->write(()->service.saveProduct(q),"Product saved."));}@FXML private void toggleProduct(){MenuModels.Product p=selected(productsTable);if(p!=null&&confirmStatus(p.name(),p.active()))write(()->{service.setProductActive(p,!p.active());return 0L;},"Product status updated.");}
    @FXML private void addVariant(){MenuModels.Product p=selected(productsTable);if(p==null){message("Select a product first.",true);return;}variantDialog(p,null).ifPresent(q->write(()->service.saveVariant(q),"Variant saved."));}@FXML private void editVariant(){MenuModels.Product p=selected(productsTable);MenuModels.Variant v=selected(variantsTable);if(p!=null&&v!=null)variantDialog(p,v).ifPresent(q->write(()->service.saveVariant(q),"Variant saved."));}@FXML private void toggleVariant(){MenuModels.Variant v=selected(variantsTable);if(v!=null&&confirmStatus(v.name(),v.active()))write(()->{service.setVariantActive(v,!v.active());return 0L;},"Variant status updated.");}
    @FXML private void addGroup(){groupDialog(null).ifPresent(q->write(()->service.saveGroup(q),"Modifier group saved."));}@FXML private void editGroup(){MenuModels.ModifierGroup g=selected(groupsTable);if(g!=null)groupDialog(g).ifPresent(q->write(()->service.saveGroup(q),"Modifier group saved."));}@FXML private void toggleGroup(){MenuModels.ModifierGroup g=selected(groupsTable);if(g!=null&&confirmStatus(g.name(),g.active()))write(()->{service.setGroupActive(g,!g.active());return 0L;},"Modifier group status updated.");}
    @FXML private void addModifier(){MenuModels.ModifierGroup g=selected(groupsTable);if(g==null){message("Select a modifier group first.",true);return;}modifierDialog(g,null).ifPresent(q->write(()->service.saveModifier(q),"Modifier saved."));}@FXML private void editModifier(){MenuModels.ModifierGroup g=selected(groupsTable);MenuModels.Modifier m=selected(modifiersTable);if(g!=null&&m!=null)modifierDialog(g,m).ifPresent(q->write(()->service.saveModifier(q),"Modifier saved."));}@FXML private void toggleModifier(){MenuModels.Modifier m=selected(modifiersTable);if(m!=null&&confirmStatus(m.name(),m.active()))write(()->{service.setModifierActive(m,!m.active());return 0L;},"Modifier status updated.");}
    @FXML private void addAssignment(){MenuModels.Product p=selected(productsTable);if(p==null){message("Select a product first.",true);return;}assignmentDialog(p,null).ifPresent(q->write(()->service.saveAssignment(q),"Modifier group assigned."));}@FXML private void editAssignment(){MenuModels.Product p=selected(productsTable);MenuModels.Assignment a=selected(assignmentsTable);if(p!=null&&a!=null)assignmentDialog(p,a).ifPresent(q->write(()->service.saveAssignment(q),"Assignment saved."));}@FXML private void toggleAssignment(){MenuModels.Assignment a=selected(assignmentsTable);if(a!=null&&confirmStatus(a.groupName(),a.active()))write(()->{service.setAssignmentActive(a,!a.active());return 0L;},"Assignment status updated.");}

    private Optional<MenuCommands.Category> categoryDialog(MenuModels.Category c){TextField name=field(c==null?null:c.name());TextArea description=area(c==null?null:c.description());Spinner<Integer> order=spinner(c==null?0:c.displayOrder());CheckBox active=check("",c==null||c.active());return formDialog(c==null?"Add category":"Edit category",List.of(row("Category name",name),row("Description",description),row("Display order",order),row("Active",active)),()->new MenuCommands.Category(c==null?null:c.id(),name.getText(),description.getText(),order.getValue(),active.isSelected(),c==null?null:c.rowVersion()));}
    private Optional<MenuCommands.Product> productDialog(MenuModels.Product p){ComboBox<MenuModels.Lookup> category=combo(catalog.categories(),lookup(catalog.categories(),p==null?null:p.categoryId()));ComboBox<MenuModels.Lookup> station=stationCombo(p==null?null:p.stationId());TextField code=field(p==null?null:p.code()),name=field(p==null?null:p.name()),image=field(p==null?null:p.imagePath());TextArea description=area(p==null?null:p.description());Spinner<Integer> order=spinner(p==null?0:p.displayOrder());CheckBox active=check("",p==null||p.active());return formDialog(p==null?"Add product":"Edit product",List.of(row("Category",category),row("Preparation station",station),row("Product code",code),row("Product name",name),row("Description",description),row("Image path",image),row("Display order",order),row("Active",active)),()->new MenuCommands.Product(p==null?null:p.id(),category.getValue()==null?0:category.getValue().id(),stationId(station),code.getText(),name.getText(),description.getText(),image.getText(),order.getValue(),active.isSelected(),p==null?null:p.rowVersion()));}
    private Optional<MenuCommands.Variant> variantDialog(MenuModels.Product product,MenuModels.Variant v){ComboBox<MenuModels.Lookup> station=stationCombo(v==null?null:v.stationId());TextField code=field(v==null?null:v.code()),name=field(v==null?null:v.name()),sku=field(v==null?null:v.sku()),price=field(v==null?"0.0000":v.price().toPlainString());Spinner<Integer> order=spinner(v==null?0:v.displayOrder());CheckBox def=check("Default active variant",v!=null&&v.defaultVariant()),active=check("Active",v==null||v.active());return formDialog(v==null?"Add variant":"Edit variant",List.of(row("Preparation station",station),row("Variant code",code),row("Variant name",name),row("SKU",sku),row("Selling price",price),row("Display order",order),row("",def),row("",active)),()->new MenuCommands.Variant(v==null?null:v.id(),product.id(),stationId(station),code.getText(),name.getText(),sku.getText(),decimal(price,"Selling price"),order.getValue(),def.isSelected(),active.isSelected(),v==null?null:v.rowVersion()));}
    private Optional<MenuCommands.Group> groupDialog(MenuModels.ModifierGroup g){TextField code=field(g==null?null:g.code()),name=field(g==null?null:g.name());TextArea description=area(g==null?null:g.description());Spinner<Integer> min=spinner(g==null?0:g.minimumSelections()),max=spinner(g==null?1:g.maximumSelections()),order=spinner(g==null?0:g.displayOrder());CheckBox active=check("Active",g==null||g.active());return formDialog(g==null?"Add modifier group":"Edit modifier group",List.of(row("Group code",code),row("Group name",name),row("Description",description),row("Minimum selections",min),row("Maximum selections",max),row("Display order",order),row("",active)),()->new MenuCommands.Group(g==null?null:g.id(),code.getText(),name.getText(),description.getText(),min.getValue(),max.getValue(),order.getValue(),active.isSelected(),g==null?null:g.rowVersion()));}
    private Optional<MenuCommands.Modifier> modifierDialog(MenuModels.ModifierGroup group,MenuModels.Modifier m){TextField code=field(m==null?null:m.code()),name=field(m==null?null:m.name()),price=field(m==null?"0.0000":m.priceAdjustment().toPlainString());Spinner<Integer> order=spinner(m==null?0:m.displayOrder());CheckBox active=check("Active",m==null||m.active());return formDialog(m==null?"Add modifier":"Edit modifier",List.of(row("Group",new Label(group.name())),row("Modifier code",code),row("Modifier name",name),row("Price adjustment",price),row("Display order",order),row("",active)),()->new MenuCommands.Modifier(m==null?null:m.id(),group.id(),code.getText(),name.getText(),decimal(price,"Price adjustment"),order.getValue(),active.isSelected(),m==null?null:m.rowVersion()));}
    private Optional<MenuCommands.Assignment> assignmentDialog(MenuModels.Product product,MenuModels.Assignment a){ComboBox<MenuModels.ModifierGroup> group=combo(catalog.groups(),group(catalog.groups(),a==null?null:a.groupId()));TextField min=field(a==null||a.minimumOverride()==null?null:a.minimumOverride().toString()),max=field(a==null||a.maximumOverride()==null?null:a.maximumOverride().toString());Spinner<Integer> order=spinner(a==null?0:a.displayOrder());CheckBox active=check("Active",a==null||a.active());return formDialog(a==null?"Assign modifier group":"Edit assignment",List.of(row("Product",new Label(product.name())),row("Modifier group",group),row("Minimum override",min),row("Maximum override",max),row("Display order",order),row("",active)),()->new MenuCommands.Assignment(a==null?null:a.id(),product.id(),group.getValue()==null?0:group.getValue().id(),integerOrNull(min,"Minimum override"),integerOrNull(max,"Maximum override"),order.getValue(),active.isSelected(),a==null?null:a.rowVersion()));}

    private <T>Optional<T>formDialog(String title,List<Node[]> rows,java.util.function.Supplier<T> result){Dialog<T>d=new Dialog<>();d.setTitle(title);d.getDialogPane().getButtonTypes().addAll(ButtonType.CANCEL,ButtonType.OK);GridPane grid=new GridPane();grid.setHgap(12);grid.setVgap(9);ColumnConstraints labels=new ColumnConstraints(155,155,155);labels.setHalignment(HPos.RIGHT);ColumnConstraints controls=new ColumnConstraints(250,340,Double.MAX_VALUE);controls.setHgrow(Priority.ALWAYS);grid.getColumnConstraints().addAll(labels,controls);for(int i=0;i<rows.size();i++){grid.add(rows.get(i)[0],0,i);grid.add(rows.get(i)[1],1,i);GridPane.setHgrow(rows.get(i)[1],Priority.ALWAYS);}grid.setMaxWidth(Double.MAX_VALUE);Label validationMessage=new Label();validationMessage.setWrapText(true);validationMessage.getStyleClass().add("status-error");VBox content=new VBox(8,grid,validationMessage);d.getDialogPane().setContent(content);d.getDialogPane().setPrefWidth(570);AtomicReference<T>validated=new AtomicReference<>();Node ok=d.getDialogPane().lookupButton(ButtonType.OK);ok.addEventFilter(ActionEvent.ACTION,event->{try{validated.set(result.get());validationMessage.setText("");}catch(RuntimeException e){validationMessage.setText(e.getMessage());event.consume();}});d.setResultConverter(button->button==ButtonType.OK?validated.get():null);return d.showAndWait();}
    private void write(java.util.concurrent.Callable<Long> action,String success){message("Saving...",false);CompletableFuture.supplyAsync(()->{try{return action.call();}catch(Exception e){throw new java.util.concurrent.CompletionException(e);}}).whenComplete((value,error)->Platform.runLater(()->{if(error!=null){fail("Unable to save this change.",error);return;}message(success,false);refresh();}));}
    private void fail(String fallback,Throwable error){Throwable cause=error;while(cause.getCause()!=null&&(cause instanceof java.util.concurrent.CompletionException||cause instanceof java.util.concurrent.ExecutionException))cause=cause.getCause();LOGGER.error("Menu operation failed ({}).",cause.getClass().getSimpleName());String safe=cause instanceof IllegalArgumentException||cause instanceof IllegalStateException||cause instanceof com.coffeeshop.exception.DatabaseException?cause.getMessage():fallback;message(safe,true);}
    private boolean confirmStatus(String name,boolean active){String action=active?"Deactivate":"Activate";Alert alert=new Alert(Alert.AlertType.CONFIRMATION,action+" "+name+"?",ButtonType.CANCEL,ButtonType.OK);alert.setHeaderText(action+" menu record");return alert.showAndWait().orElse(ButtonType.CANCEL)==ButtonType.OK;}
    private void message(String value,boolean error){messageLabel.setText(value);messageLabel.getStyleClass().setAll(error?"status-error":"status-message");}
    private static <T>T selected(TableView<T> table){return table.getSelectionModel().getSelectedItem();}private static void set(Button button,boolean enabled){button.setDisable(!enabled);}private static SimpleStringProperty text(String value){return new SimpleStringProperty(value);}private static String status(boolean active){return active?"Active":"Inactive";}private static String orDash(String value){return value==null?"-":value;}private static String money(BigDecimal value){return value.setScale(2,RoundingMode.HALF_UP).toPlainString();}private static String range(Integer min,Integer max){return min==null?"Group default":min+" - "+max;}
    private ListCell<MenuModels.Lookup>lookupCell(String nullText){return new ListCell<>(){@Override protected void updateItem(MenuModels.Lookup item,boolean empty){super.updateItem(item,empty);setText(empty?null:item==null?nullText:item.toString());}};}
    private ComboBox<MenuModels.Lookup>stationCombo(Long id){List<MenuModels.Lookup> values=new ArrayList<>();values.add(NO_STATION);values.addAll(catalog.stations());return combo(values,id==null?NO_STATION:lookup(catalog.stations(),id));}
    private static Long stationId(ComboBox<MenuModels.Lookup> box){return box.getValue()==null||box.getValue().id()==0?null:box.getValue().id();}
    private static MenuModels.Lookup lookup(List<MenuModels.Lookup> values,Long id){return id==null?null:values.stream().filter(v->v.id()==id).findFirst().orElse(null);}private static MenuModels.ModifierGroup group(List<MenuModels.ModifierGroup> values,Long id){return id==null?null:values.stream().filter(v->v.id()==id).findFirst().orElse(null);}
    private static <T>ComboBox<T>combo(Collection<T> values,T selected){ComboBox<T> box=new ComboBox<>();box.getItems().setAll(values);box.setValue(selected);box.setMaxWidth(Double.MAX_VALUE);return box;}private static TextField field(String value){TextField field=new TextField(value==null?"":value);field.setMaxWidth(Double.MAX_VALUE);return field;}private static TextArea area(String value){TextArea area=new TextArea(value==null?"":value);area.setPrefRowCount(2);area.setWrapText(true);return area;}private static Spinner<Integer>spinner(int value){Spinner<Integer> spinner=new Spinner<>(0,1_000_000,value);spinner.setEditable(true);return spinner;}private static CheckBox check(String text,boolean selected){CheckBox box=new CheckBox(text);box.setSelected(selected);return box;}private static Node[]row(String label,Node node){Label fieldLabel=new Label(label);fieldLabel.setMinWidth(Label.USE_PREF_SIZE);return new Node[]{fieldLabel,node};}
    private static BigDecimal decimal(TextField field,String label){try{return new BigDecimal(field.getText().trim());}catch(Exception e){throw new IllegalArgumentException(label+" must be a valid number.");}}private static Integer integerOrNull(TextField field,String label){if(field.getText()==null||field.getText().isBlank())return null;try{return Integer.valueOf(field.getText().trim());}catch(NumberFormatException e){throw new IllegalArgumentException(label+" must be a whole number.");}}
}
