package com.coffeeshop.controller;
import com.coffeeshop.dto.*;import com.coffeeshop.model.*;import com.coffeeshop.security.ApplicationSession;import com.coffeeshop.service.PosService;
import javafx.application.Platform;import javafx.event.ActionEvent;import javafx.fxml.FXML;import javafx.geometry.Insets;import javafx.scene.Node;import javafx.scene.control.*;import javafx.scene.layout.*;import java.math.BigDecimal;import java.math.RoundingMode;import java.util.*;import java.util.concurrent.CompletableFuture;import java.util.concurrent.atomic.AtomicReference;
/** Cashier open-order editor; payment and completion remain separate controlled workflows. */
public final class PosController {
 private record CatalogData(List<MenuCategory> categories,List<MenuVariant> menu,List<CafeTableInfo> tables){}
 private final PosService service;private final ApplicationSession session;private final List<CartLine> cart=new ArrayList<>();private List<MenuVariant> menu=List.of();
 @FXML private ComboBox<MenuCategory> categoryBox;@FXML private TextField searchField;@FXML private FlowPane productPane;@FXML private ListView<CartLine> cartList;@FXML private ChoiceBox<OrderType> orderTypeBox;@FXML private ComboBox<CafeTableInfo> tableBox;@FXML private Label subtotalLabel;@FXML private Label totalLabel;@FXML private Label statusLabel;@FXML private Button saveButton;
 public PosController(PosService s,ApplicationSession x){service=Objects.requireNonNull(s);session=Objects.requireNonNull(x);}
 @FXML private void initialize(){orderTypeBox.getItems().setAll(OrderType.values());orderTypeBox.setValue(OrderType.TAKEAWAY);orderTypeBox.valueProperty().addListener((o,a,b)->updateType());categoryBox.setCellFactory(v->categoryCell());categoryBox.setButtonCell(categoryCell());searchField.textProperty().addListener((o,a,b)->renderProducts());categoryBox.valueProperty().addListener((o,a,b)->renderProducts());loadData();updateTotals();}
 private ListCell<MenuCategory> categoryCell(){return new ListCell<>(){protected void updateItem(MenuCategory x,boolean empty){super.updateItem(x,empty);setText(empty||x==null?"All categories":x.name());}};}
 private void loadData(){setBusy(true);CompletableFuture.supplyAsync(()->new CatalogData(service.categories(),service.menu(),service.availableTables())).whenComplete((data,error)->Platform.runLater(()->{setBusy(false);if(error!=null){showError("Unable to load the POS catalog.");return;}categoryBox.getItems().setAll(data.categories());menu=data.menu();tableBox.getItems().setAll(data.tables());renderProducts();}));}
 private void renderProducts(){productPane.getChildren().clear();String q=searchField.getText()==null?"":searchField.getText().trim().toLowerCase(Locale.ROOT);MenuCategory cat=categoryBox.getValue();menu.stream().filter(v->cat==null||v.categoryId()==cat.id()).filter(v->q.isEmpty()||(v.productName()+" "+v.variantName()).toLowerCase(Locale.ROOT).contains(q)).forEach(v->{Button b=new Button(v.productName()+"\n"+v.variantName()+"  ·  "+v.price().setScale(2,RoundingMode.HALF_UP));b.getStyleClass().add("product-card");b.setOnAction(e->add(v));productPane.getChildren().add(b);});if(productPane.getChildren().isEmpty())productPane.getChildren().add(new Label("No active menu products match this view."));}
 private void add(MenuVariant v){CompletableFuture.supplyAsync(()->service.modifierGroups(v.productId())).whenComplete((groups,error)->Platform.runLater(()->{if(error!=null){showError("Unable to load choices for this item.");return;}if(groups.isEmpty()){addLine(v,List.of());return;}modifierDialog(v,groups).ifPresent(selected->addLine(v,selected));}));}
 private void addLine(MenuVariant variant,List<SelectedModifier> modifiers){cart.stream().filter(line->line.sameSelection(variant,modifiers)).findFirst().ifPresentOrElse(CartLine::increment,()->cart.add(new CartLine(variant,modifiers)));refreshCart();}
 private Optional<List<SelectedModifier>> modifierDialog(MenuVariant variant,List<PosModifierGroup> groups){
  Dialog<List<SelectedModifier>> dialog=new Dialog<>();dialog.setTitle("Customize item");dialog.setHeaderText(variant.productName()+" · "+variant.variantName()+"   Base "+money(variant.price()));dialog.getDialogPane().getButtonTypes().addAll(ButtonType.CANCEL,new ButtonType("Add to order",ButtonBar.ButtonData.OK_DONE));
  VBox groupBox=new VBox(12);Map<PosModifierGroup,List<CheckBox>> controls=new LinkedHashMap<>();Label total=new Label();total.getStyleClass().add("modifier-total");Label validation=new Label();validation.getStyleClass().add("status-error");validation.setWrapText(true);
  for(PosModifierGroup group:groups){VBox box=new VBox(6);Label title=new Label(group.name()+"  "+selectionRule(group));title.getStyleClass().add("modifier-group-title");List<CheckBox> checks=new ArrayList<>();for(PosModifierOption option:group.options()){CheckBox check=new CheckBox(option.name()+(option.priceAdjustment().signum()==0?"":"  +"+money(option.priceAdjustment())));check.setUserData(option);checks.add(check);box.getChildren().add(check);}if(checks.isEmpty()){Label unavailable=new Label("No active options are currently available.");unavailable.getStyleClass().add("empty-copy");box.getChildren().add(unavailable);}controls.put(group,checks);groupBox.getChildren().add(box);}
  Runnable update=()->{controls.forEach((group,checks)->{long count=checks.stream().filter(CheckBox::isSelected).count();checks.forEach(check->check.setDisable(!check.isSelected()&&count>=group.maximumSelections()));});BigDecimal amount=selectedOptions(controls).stream().map(PosModifierOption::priceAdjustment).reduce(variant.price(),BigDecimal::add);total.setText("Item price  "+money(amount));};controls.values().stream().flatMap(Collection::stream).forEach(check->check.selectedProperty().addListener((o,a,b)->update.run()));update.run();
  ScrollPane scroll=new ScrollPane(groupBox);scroll.setFitToWidth(true);scroll.setHbarPolicy(ScrollPane.ScrollBarPolicy.NEVER);scroll.setPrefViewportHeight(Math.min(360,120+groups.size()*70));scroll.getStyleClass().add("transparent-scroll");VBox content=new VBox(10,scroll,total,validation);content.setPadding(new Insets(4));dialog.getDialogPane().setContent(content);dialog.getDialogPane().setPrefWidth(500);
  AtomicReference<List<SelectedModifier>> result=new AtomicReference<>();Node confirm=dialog.getDialogPane().lookupButton(dialog.getDialogPane().getButtonTypes().get(1));confirm.addEventFilter(ActionEvent.ACTION,event->{try{result.set(service.validateModifierSelection(groups,selectedOptions(controls)));validation.setText("");}catch(IllegalArgumentException e){validation.setText(e.getMessage());event.consume();}});dialog.setResultConverter(button->button.getButtonData()==ButtonBar.ButtonData.OK_DONE?result.get():null);return dialog.showAndWait();
 }
 private static List<PosModifierOption> selectedOptions(Map<PosModifierGroup,List<CheckBox>> controls){return controls.values().stream().flatMap(Collection::stream).filter(CheckBox::isSelected).map(check->(PosModifierOption)check.getUserData()).toList();}
 private static String selectionRule(PosModifierGroup group){if(group.minimumSelections()==0)return group.maximumSelections()==1?"(optional, choose up to 1)":"(optional, choose up to "+group.maximumSelections()+")";return "(choose "+group.minimumSelections()+(group.minimumSelections()==group.maximumSelections()?"":"–"+group.maximumSelections())+")";}
 private static String money(BigDecimal value){return value.setScale(2,RoundingMode.HALF_UP).toPlainString();}
 @FXML private void increase(){selected().ifPresent(CartLine::increment);refreshCart();}@FXML private void decrease(){selected().ifPresent(CartLine::decrement);refreshCart();}@FXML private void remove(){selected().ifPresent(cart::remove);refreshCart();}
 @FXML private void clearCart(){if(cart.isEmpty())return;Alert a=new Alert(Alert.AlertType.CONFIRMATION,"Remove every item from this order?",ButtonType.CANCEL,ButtonType.OK);a.setHeaderText("Clear current order");if(a.showAndWait().orElse(ButtonType.CANCEL)==ButtonType.OK){cart.clear();refreshCart();}}
 private Optional<CartLine> selected(){return Optional.ofNullable(cartList.getSelectionModel().getSelectedItem());}private void refreshCart(){cartList.getItems().setAll(cart);updateTotals();}
 private void updateTotals(){var t=service.subtotal(cart).setScale(2,RoundingMode.HALF_UP);subtotalLabel.setText(t.toPlainString());totalLabel.setText(t.toPlainString());}
 private void updateType(){boolean dine=orderTypeBox.getValue()==OrderType.DINE_IN;tableBox.setVisible(dine);tableBox.setManaged(dine);if(dine)loadTables();}
 private void loadTables(){CompletableFuture.supplyAsync(service::availableTables).whenComplete((v,e)->Platform.runLater(()->{if(e==null)tableBox.getItems().setAll(v);else showError("Unable to refresh available tables.");}));}
 @FXML private void saveOrder(){DeliveryInfo delivery=null;if(orderTypeBox.getValue()==OrderType.DELIVERY){delivery=deliveryDialog().orElse(null);if(delivery==null)return;}var user=session.currentUser().orElseThrow();Long table=tableBox.getValue()==null?null:tableBox.getValue().id();var request=new CreateOrderRequest(user.userId(),orderTypeBox.getValue(),table,delivery,cart);setBusy(true);CompletableFuture.supplyAsync(()->service.saveOpenOrder(request)).whenComplete((n,e)->Platform.runLater(()->{setBusy(false);if(e!=null){Throwable cause=e.getCause();showError(cause instanceof IllegalArgumentException?cause.getMessage():"Unable to save the order right now.");return;}cart.clear();refreshCart();statusLabel.getStyleClass().setAll("status-message");statusLabel.setText("Open order "+n+" saved. Payment has not been recorded.");loadTables();}));}
 private Optional<DeliveryInfo> deliveryDialog(){Dialog<DeliveryInfo>d=new Dialog<>();d.setTitle("Delivery details");d.getDialogPane().getButtonTypes().addAll(ButtonType.CANCEL,ButtonType.OK);TextField n=new TextField(),p=new TextField(),a=new TextField(),c=new TextField();n.setPromptText("Recipient name");p.setPromptText("Phone");a.setPromptText("Address line 1");c.setPromptText("City");d.getDialogPane().setContent(new javafx.scene.layout.VBox(10,n,p,a,c));d.setResultConverter(b->b==ButtonType.OK?new DeliveryInfo(n.getText(),p.getText(),a.getText(),c.getText()):null);return d.showAndWait();}
 private void setBusy(boolean b){saveButton.setDisable(b);}@FXML private void refresh(){loadData();}private void showError(String m){statusLabel.setText(m);statusLabel.getStyleClass().setAll("status-error");}
}
