package com.coffeeshop.controller;
import com.coffeeshop.dto.TableManagementCommands;import com.coffeeshop.model.*;import com.coffeeshop.model.TableManagementModels.CafeTable;import com.coffeeshop.service.TableManagementService;import javafx.application.Platform;import javafx.beans.property.SimpleStringProperty;import javafx.fxml.FXML;import javafx.geometry.Insets;import javafx.scene.control.*;import javafx.scene.layout.*;import java.util.*;import java.util.concurrent.CompletableFuture;import java.util.function.Consumer;
public final class TablesController{
 private static final List<String> STATUSES=List.of("AVAILABLE","OCCUPIED","RESERVED","OUT_OF_SERVICE");private final TableManagementService service;private final Consumer<NavigationItem> navigator;@FXML private FlowPane tablePane;@FXML private TableView<CafeTable> managementTable;@FXML private TableColumn<CafeTable,String> codeColumn,nameColumn,capacityColumn,statusColumn,activeColumn;@FXML private Label messageLabel;@FXML private Button editButton,activeButton;
 public TablesController(TableManagementService s,Consumer<NavigationItem> n){service=Objects.requireNonNull(s);navigator=Objects.requireNonNull(n);}
 @FXML private void initialize(){codeColumn.setCellValueFactory(v->text(v.getValue().code()));nameColumn.setCellValueFactory(v->text(v.getValue().name()));capacityColumn.setCellValueFactory(v->text(Integer.toString(v.getValue().capacity())));statusColumn.setCellValueFactory(v->text(v.getValue().status().replace('_',' ')));activeColumn.setCellValueFactory(v->text(v.getValue().active()?"Active":"Inactive"));managementTable.getSelectionModel().selectedItemProperty().addListener((o,a,b)->selection(b));refresh();}
 @FXML private void refresh(){messageLabel.setText("Loading cafe tables…");CompletableFuture.supplyAsync(service::tables).whenComplete((values,error)->Platform.runLater(()->{if(error!=null){messageLabel.setText("Unable to load cafe tables.");return;}managementTable.getItems().setAll(values);tablePane.getChildren().clear();values.stream().filter(CafeTable::active).forEach(this::card);messageLabel.setText(values.isEmpty()?"No cafe tables are configured.":tablePane.getChildren().isEmpty()?"No active cafe tables are configured.":"");selection(managementTable.getSelectionModel().getSelectedItem());}));}
 private void card(CafeTable t){Button b=new Button(t.name()+"\n"+t.status().replace('_',' ')+" · "+t.capacity()+" seats");b.getStyleClass().addAll("table-card","table-"+t.status().toLowerCase());b.setOnAction(e->navigator.accept("AVAILABLE".equals(t.status())?NavigationItem.POS:NavigationItem.ORDERS));tablePane.getChildren().add(b);}
 @FXML private void addTable(){editor(null).ifPresent(this::save);}@FXML private void editTable(){CafeTable t=managementTable.getSelectionModel().getSelectedItem();if(t!=null)editor(t).ifPresent(this::save);}@FXML private void toggleActive(){CafeTable t=managementTable.getSelectionModel().getSelectedItem();if(t==null)return;if(t.active()&&!confirm("Deactivate "+t.name()+"?","The table will be hidden from POS."))return;write(()->service.setActive(t,!t.active()),t.active()?"Table deactivated.":"Table activated.");}
 private void save(TableManagementCommands.SaveTable q){write(()->service.saveTable(q),"Table saved.");}private void write(Runnable task,String success){CompletableFuture.runAsync(task).whenComplete((v,e)->Platform.runLater(()->{if(e==null){refresh();messageLabel.setText(success);}else messageLabel.setText(message(e));}));}
 private Optional<TableManagementCommands.SaveTable> editor(CafeTable t){Dialog<TableManagementCommands.SaveTable>d=new Dialog<>();d.setTitle(t==null?"Add cafe table":"Edit cafe table");d.setHeaderText("Cafe table details");ButtonType save=new ButtonType("Save",ButtonBar.ButtonData.OK_DONE);d.getDialogPane().getButtonTypes().addAll(ButtonType.CANCEL,save);TextField code=new TextField(t==null?"":t.code()),name=new TextField(t==null?"":t.name());Spinner<Integer>capacity=new Spinner<>(1,999,t==null?2:t.capacity()),order=new Spinner<>(0,9999,t==null?0:t.displayOrder());ComboBox<String>status=new ComboBox<>();status.getItems().setAll(STATUSES);status.setValue(t==null?"AVAILABLE":t.status());CheckBox active=new CheckBox("Active");active.setSelected(t==null||t.active());GridPane form=new GridPane();form.setHgap(12);form.setVgap(10);form.setPadding(new Insets(8));field(form,0,"Table code",code);field(form,1,"Table name",name);field(form,2,"Capacity",capacity);field(form,3,"Status",status);field(form,4,"Display order",order);form.add(active,1,5);d.getDialogPane().setContent(form);d.getDialogPane().setPrefWidth(440);d.setResultConverter(b->b==save?new TableManagementCommands.SaveTable(t==null?null:t.id(),code.getText(),name.getText(),capacity.getValue(),status.getValue(),order.getValue(),active.isSelected(),t==null?null:t.rowVersion()):null);return d.showAndWait();}
 private static void field(GridPane p,int row,String label,Control c){p.add(new Label(label),0,row);c.setMaxWidth(Double.MAX_VALUE);p.add(c,1,row);}private void selection(CafeTable t){editButton.setDisable(t==null);activeButton.setDisable(t==null);activeButton.setText(t==null||t.active()?"Deactivate":"Activate");}private static SimpleStringProperty text(String v){return new SimpleStringProperty(v);}private static boolean confirm(String h,String c){Alert a=new Alert(Alert.AlertType.CONFIRMATION,c,ButtonType.CANCEL,ButtonType.OK);a.setHeaderText(h);return a.showAndWait().orElse(ButtonType.CANCEL)==ButtonType.OK;}private static String message(Throwable e){Throwable x=e;while(x.getCause()!=null)x=x.getCause();return x instanceof IllegalArgumentException||x instanceof IllegalStateException?x.getMessage():"Unable to update the cafe table.";}
}
